import React,{useEffect,useRef,useState} from "react";
import {AlertTriangle, ArrowRight, Ban, CheckCircle2, Download, Edit3, FileText, Filter, Mail, MapPin, MessageSquare, Plus, Search, ShieldCheck, ShoppingCart, Upload, UserPlus, Users, XCircle} from "lucide-react";
import {displayTime,formatMoney,orderTotal} from "../data";
import type {CustomerRecord} from "../phase2Data";
import {useDemo,canAct} from "../store";
import {Bars,Card,Chip,DetailLine,Empty,IconStat,Initials,Modal,Ring,SearchBox,SelectBox,Tabs} from "../ui";
const counties=["Nairobi","Kiambu","Mombasa","Nakuru","Kisumu","Machakos"];
export function CustomersScreen({navigate,county,globalSearch,toast}:{navigate:(s:string)=>void;county:string;globalSearch:string;toast:(s:string)=>void}){
 const {data,act,role}=useDemo(),all=data.phase2.customers,canManage=canAct(role,"customer"),canDelete=canAct(role,"delete");
 const [tab,setTab]=useState("all"),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[localCounty,setLocalCounty]=useState("all"),[selectedId,setSelectedId]=useState<string|null>(null),[detail,setDetail]=useState("overview"),[page,setPage]=useState(1);
 const [modal,setModal]=useState<"add"|"edit"|"status"|"note"|"address"|"import"|null>(null),[nextStatus,setNextStatus]=useState<CustomerRecord["status"]>("ACTIVE"),[reason,setReason]=useState(""),[form,setForm]=useState({name:"",phone:"",email:"",county:"Nairobi"}),[address,setAddress]=useState({label:"Home",area:"",county:"Nairobi"}),[csvText,setCsvText]=useState(""),[importError,setImportError]=useState("");
 const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(globalSearch)setSearch(globalSearch);},[globalSearch]);
 useEffect(()=>setPage(1),[tab,search,status,localCounty,county]);
 const filtered=all.filter(c=>(tab==="all"||tab==="active"&&c.status==="ACTIVE"||tab==="restricted"&&c.status==="RESTRICTED"||tab==="suspended"&&c.status==="SUSPENDED"||tab==="new"&&Date.parse(c.joinedAt)>Date.parse("2026-09-01T00:00:00Z"))&&(status==="all"||c.status===status)&&(localCounty==="all"||c.county===localCounty)&&(county==="all"||c.county===county)&&(c.id+" "+c.name+" "+c.phone+" "+c.email).toLowerCase().includes(search.toLowerCase()));
 const showing=filtered.slice((page-1)*10,page*10),pages=Math.ceil(filtered.length/10)||1;
 const selected=all.find(c=>c.id===selectedId)||showing[0];
 const orders=selected?data.orders.filter(o=>o.customer===selected.name):[];
 const support=selected?data.phase2.support.filter(x=>x.participantType==="Customer"&&x.participantName===selected.name):[];
 const active=all.filter(x=>x.status==="ACTIVE").length,restricted=all.filter(x=>x.status==="RESTRICTED").length,suspended=all.filter(x=>x.status==="SUSPENDED").length;
 const openAdd=()=>{setForm({name:"",phone:"",email:"",county:"Nairobi"});setModal("add");};
 const openEdit=()=>{if(!selected)return;setForm({name:selected.name,phone:selected.phone,email:selected.email,county:selected.county});setReason("");setModal("edit");};
 const save=()=>{
  if(!canManage)return;
  if(modal==="add"){if(form.name.trim().length<3||!form.email.includes("@")||form.phone.trim().length<8)return;act({type:"PHASE2_CUSTOMER_CREATE",...form});setTab("all");toast("Demo customer created.");}
  if(modal==="edit"&&selected){if(form.name.trim().length<3||!form.email.includes("@")||reason.trim().length<3)return;act({type:"PHASE2_CUSTOMER_EDIT",id:selected.id,...form,reason});toast("Customer profile corrected and logged.");}
  if(modal==="status"&&selected){if(reason.trim().length<3)return;act({type:"PHASE2_CUSTOMER_STATUS",id:selected.id,status:nextStatus,reason});toast("Customer status updated.");}
  if(modal==="note"&&selected){if(reason.trim().length<2)return;act({type:"PHASE2_CUSTOMER_NOTE",id:selected.id,note:reason});toast("Private customer note added.");}
  if(modal==="address"&&selected){if(address.area.trim().length<2)return;act({type:"PHASE2_CUSTOMER_ADDRESS",id:selected.id,...address});toast("Delivery address added.");}
  setModal(null);setReason("");
 };
 const prepareStatus=(s:CustomerRecord["status"])=>{setNextStatus(s);setReason("");setModal("status");};
 const gotoOrder=(id:string)=>{sessionStorage.setItem("deetoo.demo.focusOrder",id);navigate("orders");};
 const exportRows=()=>{const csv=["ID,Name,Email,Phone,County,Status",...filtered.map(x=>[x.id,x.name,x.email,x.phone,x.county,x.status].map(v=>'"'+v.replaceAll('"','""')+'"').join(","))].join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="deetoo-demo-customers.csv";a.click();URL.revokeObjectURL(url);toast("Customer demo directory exported.");};
 const validateImport=()=>{const lines=csvText.trim().split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const header=lines.shift()?.toLowerCase();if(header!=="name,email,phone,county"){setImportError("Expected header: name,email,phone,county");return null;}const rows=lines.slice(0,100).map(l=>l.split(",").map(x=>x.trim()));if(rows.length===0||rows.some(r=>r.length!==4||r[0].length<3||!r[1].includes("@")||r[2].length<8||!counties.includes(r[3]))){setImportError("At least one row is invalid. Use a supported county and valid name/email/phone.");return null;}setImportError("");return rows;};
 const importRows=()=>{if(!canManage)return;const rows=validateImport();if(!rows)return;let existing=new Set(all.map(c=>c.email.toLowerCase()));let added=0;for(const [name,email,phone,countyValue] of rows){if(existing.has(email.toLowerCase()))continue;act({type:"PHASE2_CUSTOMER_CREATE",name,email,phone,county:countyValue});existing.add(email.toLowerCase());added++;}toast(added+" simulated customers imported.");setModal(null);setCsvText("");setTab("all");};
 return <div className="dn-screen" data-testid="screen-customers">
  <div className="dn-title-row"><div><h1>Customer Management</h1><p>View and manage customer accounts, orders, support history and account status.</p></div><div className="dn-title-buttons"><button className="dn-btn outline" onClick={exportRows}><Download size={15}/> Export</button><button className="dn-btn outline" disabled={!canManage} onClick={()=>{setCsvText("");setImportError("");setModal("import");}}><Upload size={15}/> Import</button><button className="dn-btn primary" disabled={!canManage} onClick={openAdd}><Plus size={15}/> Add Customer</button></div></div>
  <div className="dn-metrics five">
   <IconStat label="Total Customers" value={all.filter(x=>x.status!=="DELETED").length} icon={<Users/>} change="In demo directory"/>
   <IconStat label="Active Customers" value={active} icon={<CheckCircle2/>}/>
   <IconStat label="New Sign Ups" value={all.filter(x=>Date.parse(x.joinedAt)>Date.parse("2026-09-01T00:00:00Z")).length} tone="blue" icon={<UserPlus/>}/>
   <IconStat label="Restricted Accounts" value={restricted} tone="amber" icon={<AlertTriangle/>}/>
   <IconStat label="Suspended Accounts" value={suspended} tone="red" icon={<Ban/>}/>
  </div>
  <div className="dn-customer-workspace">
   <div className="dn-customer-left">
    <Card className="dn-customer-directory">
     <Tabs ariaLabel="Customer sections" value={tab} onChange={setTab} tabs={[{key:"all",label:"All Customers ("+all.length+")"},{key:"active",label:"Active ("+active+")"},{key:"restricted",label:"Restricted ("+restricted+")"},{key:"suspended",label:"Suspended ("+suspended+")"},{key:"new",label:"New Sign Ups"}]}/>
     <div className="dn-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search customers by name, phone, email..."/><SelectBox label="Customer status" value={status} onChange={setStatus} options={[{value:"all",label:"All Statuses"},...["ACTIVE","RESTRICTED","SUSPENDED","DELETED"].map(s=>({value:s,label:s}))]}/><SelectBox label="Customer county" value={localCounty} onChange={setLocalCounty} options={[{value:"all",label:"All Counties"},...counties.map(s=>({value:s,label:s}))]}/></div>
     <div className="dn-table-scroll"><table className="dn-table dn-customer-table"><thead><tr><th>Customer</th><th>Phone</th><th>Email</th><th>Location</th><th>Status</th><th>Orders</th><th>Total Spent</th><th>Joined</th></tr></thead><tbody>{showing.map(c=>{const list=data.orders.filter(o=>o.customer===c.name);return <tr key={c.id} className={selected?.id===c.id?"selected":""} tabIndex={0} onClick={()=>{setSelectedId(c.id);setDetail("overview");}} onKeyDown={e=>e.key==="Enter"&&setSelectedId(c.id)}><td><div className="dn-cell-person"><Initials name={c.name}/><div><b>{c.name}</b><small>#{c.id}</small></div></div></td><td>{c.phone}</td><td>{c.email}</td><td>{c.county}</td><td><Chip value={c.status}/></td><td>{list.length}</td><td>{formatMoney(list.reduce((a,o)=>a+orderTotal(o),0))}</td><td>{displayTime(c.joinedAt)}</td></tr>;})}</tbody></table></div>{!showing.length&&<Empty label="No customers match these filters"/>}
     <div className="dn-pagination"><span>Showing {filtered.length?(page-1)*10+1:0}–{Math.min(page*10,filtered.length)} of {filtered.length} customers</span><div><button disabled={page===1} onClick={()=>setPage(v=>v-1)}>‹</button>{Array.from({length:Math.min(pages,5)},(_,i)=><button key={i} className={page===i+1?"selected":""} onClick={()=>setPage(i+1)}>{i+1}</button>)}<button disabled={page>=pages} onClick={()=>setPage(v=>v+1)}>›</button></div></div>
    </Card>
    <div className="dn-customer-bottom-left"><Card title="Order History" desc="Illustrative recent demo order volumes"><Bars values={[12,16,10,18,19,14,16,20,23,14,24,20]} labels={["Apr","","","","Jun","","","","Aug","","","Sep"]}/></Card><Card title="Spending by Category"><Ring number={formatMoney(orders.reduce((a,o)=>a+orderTotal(o),0))} label="Demo orders" parts={[{name:"Restaurants",value:45,color:"#008f59"},{name:"Groceries",value:22,color:"#147bf0"},{name:"Pharmacy",value:12,color:"#ff9d24"},{name:"Other",value:21,color:"#a06def"}]}/></Card></div>
   </div>
   <div className="dn-customer-right">
    <Card className="dn-customer-detail">
     {selected?<><div className="dn-customer-top"><Initials name={selected.name}/><div><h2>{selected.name}</h2><p>#{selected.id} · <Chip value={selected.status}/></p><p>★ 4.8 (demo profile) · {selected.email}</p><p>☎ {selected.phone} · 📍 {selected.county}, Kenya</p></div><button className="dn-btn outline" onClick={openEdit} disabled={!canManage}><Edit3 size={14}/> Edit</button></div>
      <Tabs ariaLabel="Customer details" value={detail} onChange={setDetail} tabs={[{key:"overview",label:"Overview"},{key:"orders",label:"Orders ("+orders.length+")"},{key:"addresses",label:"Addresses ("+selected.addresses.length+")"},{key:"payments",label:"Payments"},{key:"support",label:"Support ("+support.length+")"},{key:"activity",label:"Activity"},{key:"settings",label:"Settings"}]}/>
      {detail==="overview"&&<div className="dn-customer-info"><div className="dn-innerbox"><div className="dn-inline-heading"><h3>Customer Summary</h3><button className="dn-smalloutline" disabled={!canManage} onClick={openEdit}>Edit</button></div><DetailLine label="Full name">{selected.name}</DetailLine><DetailLine label="Phone number">{selected.phone}</DetailLine><DetailLine label="Email address">{selected.email}</DetailLine><DetailLine label="County">{selected.county}</DetailLine><DetailLine label="Joined">{displayTime(selected.joinedAt)}</DetailLine><DetailLine label="Account status"><Chip value={selected.status}/></DetailLine><DetailLine label="Verification">{selected.verified?"Verified":"Pending"}</DetailLine><DetailLine label="Total orders">{orders.length}</DetailLine><DetailLine label="Total spent">{formatMoney(orders.reduce((a,o)=>a+orderTotal(o),0))}</DetailLine></div>
       <div className="dn-customer-overview-side"><div className="dn-innerbox"><h3>Quick Actions</h3><div className="dn-quick-grid"><button className="dn-btn primary" onClick={()=>navigate("support")}><MessageSquare size={14}/> Send Message</button><button className="dn-btn outline" onClick={()=>setDetail("orders")}>View All Orders</button><button className="dn-btn outline" onClick={openEdit} disabled={!canManage}>Edit Account</button><button className="dn-btn outline" onClick={()=>{setReason("");setModal("note");}} disabled={!canManage}>Add Note</button><button className="dn-btn red" onClick={()=>prepareStatus("RESTRICTED")} disabled={!canManage||selected.status==="RESTRICTED"}>Restrict Account</button><button className="dn-btn red" onClick={()=>prepareStatus("SUSPENDED")} disabled={!canManage||selected.status==="SUSPENDED"}>Suspend Account</button></div></div>
       <div className="dn-innerbox"><div className="dn-inline-heading"><h3>Addresses ({selected.addresses.length})</h3><button className="dn-text-btn" disabled={!canManage} onClick={()=>setModal("address")}>Manage</button></div>{selected.addresses.map(a=><div className="dn-address-mini" key={a.id}><MapPin size={16}/><div><b>{a.label}</b><p>{a.area}, {a.county}</p></div>{a.isDefault&&<Chip value="Default"/>}</div>)}{selected.addresses.length===0&&<Empty label="No delivery addresses"/>}</div></div>
      </div>}
      {detail==="orders"&&<div className="dn-panel-information"><h3>Recent Customer Orders</h3><div className="dn-table-scroll"><table className="dn-table"><thead><tr><th>Order</th><th>Merchant</th><th>Status</th><th>Total</th><th>Action</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>#{o.id}</td><td>{o.merchant}</td><td><Chip value={o.status}/></td><td>{formatMoney(orderTotal(o))}</td><td><button className="dn-smalloutline" onClick={()=>gotoOrder(o.id)}>View</button></td></tr>)}</tbody></table></div>{orders.length===0&&<Empty label="Customer has no demo orders"/>}</div>}
      {detail==="addresses"&&<div className="dn-panel-information"><div className="dn-inline-heading"><h3>Saved Addresses</h3><button className="dn-btn primary" disabled={!canManage} onClick={()=>setModal("address")}><Plus size={13}/> Add Address</button></div>{selected.addresses.map(a=><div className="dn-address-mini" key={a.id}><MapPin size={17}/><div><b>{a.label}</b><p>{a.area}, {a.county}</p></div>{a.isDefault&&<Chip value="Default"/>}</div>)}</div>}
      {detail==="payments"&&<div className="dn-panel-information"><DetailLine label="Paid orders">{orders.filter(o=>o.paymentStatus==="Paid").length}</DetailLine><DetailLine label="Total order value">{formatMoney(orders.reduce((a,o)=>a+orderTotal(o),0))}</DetailLine><p>Financial transactions and payment instruments are part of the approved Phase 3 frontend.</p></div>}
      {detail==="support"&&<div className="dn-panel-information"><h3>Support history</h3>{support.map(c=><button className="dn-support-related" key={c.id} onClick={()=>{sessionStorage.setItem("deetoo.demo.focusSupport",c.id);navigate("support");}}><b>{c.id}</b><span>{c.subject}</span><Chip value={c.status}/></button>)}{!support.length&&<Empty label="No support cases yet"/>}</div>}
      {detail==="activity"&&<div className="dn-panel-information"><h3>Admin Audit History (demo)</h3>{selected.audit.map((a,i)=><div className="dn-history-row" key={i}><b>{a.action}</b><span>{a.reason}</span><small>{displayTime(a.at)}</small></div>)}{!selected.audit.length&&<Empty label="No administrative changes recorded"/>}</div>}
      {detail==="settings"&&<div className="dn-panel-information"><h3>Account Controls</h3><DetailLine label="Status"><Chip value={selected.status}/></DetailLine><button className="dn-btn primary" disabled={!canManage||selected.status==="ACTIVE"} onClick={()=>prepareStatus("ACTIVE")}>Reactivate Customer</button><button className="dn-btn red" disabled={!canManage||selected.status==="SUSPENDED"} onClick={()=>prepareStatus("SUSPENDED")}>Suspend</button><button className="dn-btn red" disabled={!canDelete||selected.status==="DELETED"} onClick={()=>prepareStatus("DELETED")}>Delete Customer (soft delete)</button><p>Deletions are simulated soft-deletes with an audit trail. Real removal requires a future backend and retention-policy review.</p></div>}
     </>:<Empty label="Choose a customer from the directory"/>}
    </Card>
    <div className="dn-customer-right-bottom"><Card title="Recent Orders" action={<button className="dn-text-btn" onClick={()=>setDetail("orders")}>View All →</button>}>{orders.slice(0,4).map(o=><button className="dn-mini-result" key={o.id} onClick={()=>gotoOrder(o.id)}><b>#{o.id}</b><span>{o.merchant}</span><Chip value={o.status}/></button>)}{orders.length===0&&<Empty/>}</Card><Card title="Support History" action={<button className="dn-text-btn" onClick={()=>setDetail("support")}>View All →</button>}>{support.slice(0,4).map(c=><button className="dn-mini-result" key={c.id} onClick={()=>{sessionStorage.setItem("deetoo.demo.focusSupport",c.id);navigate("support");}}><b>#{c.id}</b><span>{c.subject}</span><Chip value={c.status}/></button>)}{!support.length&&<Empty label="No support history"/>}</Card></div>
   </div>
  </div>
  {(modal==="add"||modal==="edit")&&<Modal title={modal==="add"?"Add customer":"Edit customer profile"} subtitle="Super Admin demo authority only" onClose={()=>setModal(null)} onConfirm={save} confirmText={modal==="add"?"Create customer":"Save changes"} disabled={!canManage||form.name.trim().length<3||!form.email.includes("@")||form.phone.trim().length<8||modal==="edit"&&reason.trim().length<3}>{(["name","phone","email"] as const).map(k=><label className="dn-field" key={k}>{k[0].toUpperCase()+k.slice(1)}<input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label className="dn-field">County<select value={form.county} onChange={e=>setForm({...form,county:e.target.value})}>{counties.map(x=><option key={x}>{x}</option>)}</select></label>{modal==="edit"&&<label className="dn-field">Required audit reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label>}</Modal>}
  {modal==="status"&&selected&&<Modal title="Change customer account status" subtitle={selected.name+" · Super Admin authority required"} onClose={()=>setModal(null)} onConfirm={save} confirmText="Confirm status change" disabled={!canManage||reason.trim().length<3} danger={nextStatus!=="ACTIVE"}><label className="dn-field">New status<select value={nextStatus} onChange={e=>setNextStatus(e.target.value as CustomerRecord["status"])}>{["ACTIVE","RESTRICTED","SUSPENDED","DELETED"].map(x=><option key={x}>{x}</option>)}</select></label><label className="dn-field">Reason (required)<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain the account intervention"/></label><p>A deleted account is only marked as deleted inside this demo; no backend account is affected.</p></Modal>}
  {modal==="note"&&selected&&<Modal title="Add internal customer note" onClose={()=>setModal(null)} onConfirm={save} disabled={!canManage||reason.trim().length<2} confirmText="Save note"><label className="dn-field">Note<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label></Modal>}
  {modal==="address"&&selected&&<Modal title="Add customer address" subtitle={selected.name} onClose={()=>setModal(null)} onConfirm={save} disabled={!canManage||address.area.trim().length<2} confirmText="Save address"><label className="dn-field">Label<input value={address.label} onChange={e=>setAddress({...address,label:e.target.value})}/></label><label className="dn-field">Area<input value={address.area} onChange={e=>setAddress({...address,area:e.target.value})}/></label><label className="dn-field">County<select value={address.county} onChange={e=>setAddress({...address,county:e.target.value})}>{counties.map(x=><option key={x}>{x}</option>)}</select></label></Modal>}
  {modal==="import"&&<Modal title="Import customer demo CSV" subtitle="Super Admin only · maximum 100 rows per import" onClose={()=>setModal(null)} onConfirm={importRows} confirmText="Import customers" disabled={!canManage||!csvText.trim()}><p>Upload or paste CSV with headers: name,email,phone,county. This only creates local demo records.</p><input type="file" accept=".csv,text/csv" ref={fileRef} onChange={e=>{const file=e.target.files?.[0];if(file){file.text().then(t=>{setCsvText(t);setImportError("");}).catch(()=>setImportError("Could not read CSV file."));}}}/><label className="dn-field">CSV content<textarea value={csvText} rows={7} onChange={e=>setCsvText(e.target.value)} placeholder={"name,email,phone,county\nJane Wanjiku,jane@example.com,+254712345678,Nairobi"}/></label>{importError&&<p role="alert" className="danger-text">{importError}</p>}</Modal>}
 </div>;
}
