import React,{useEffect,useMemo,useState} from "react";
import {AlertTriangle, ArrowRight, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Filter, MessageSquare, Plus, Search, ShieldAlert, UserRound, X} from "lucide-react";
import {displayTime} from "../data";
import type {IncidentCase,IncidentStatus,Severity} from "../phase2Data";
import {useDemo,canAct} from "../store";
import {Bars,Card,Chip,DetailLine,Empty,IconStat,Initials,Modal, Ring,SearchBox,SelectBox,Tabs} from "../ui";
const statuses:IncidentStatus[]=["OPEN","ACKNOWLEDGED","INVESTIGATING","ACTION_REQUIRED","MONITORING","RESOLVED","CLOSED"];
const staff=["Unassigned","James K.","Grace N.","Collins M.","Mary A.","Daniel O.","Alex T."];
export function IncidentsScreen({navigate,globalSearch,toast}:{navigate:(id:string)=>void;globalSearch:string;toast:(s:string)=>void}){
 const {data,act,role}=useDemo(),records=data.phase2.incidents,canManage=canAct(role,"incident");
 const [tab,setTab]=useState("all"),[query,setQuery]=useState(""),[severity,setSeverity]=useState("all"),[kind,setKind]=useState("all"),[assignee,setAssignee]=useState("all"),[selectedId,setSelectedId]=useState<string|null>(null),[panel,setPanel]=useState("overview"),[page,setPage]=useState(1);
 const [modal,setModal]=useState<"create"|"status"|"note"|null>(null),[reason,setReason]=useState(""),[targetStatus,setTargetStatus]=useState<IncidentStatus>("INVESTIGATING"),[newTitle,setNewTitle]=useState(""),[newType,setNewType]=useState("Delivery"),[newSeverity,setNewSeverity]=useState<Severity>("MEDIUM"),[newOrder,setNewOrder]=useState(""),[newDescription,setNewDescription]=useState("");
 useEffect(()=>{if(globalSearch)setQuery(globalSearch);},[globalSearch]);
 useEffect(()=>setPage(1),[tab,query,severity,kind,assignee]);
 const counts={open:records.filter(x=>x.status==="OPEN").length,investigating:records.filter(x=>x.status==="INVESTIGATING").length,action:records.filter(x=>x.status==="ACTION_REQUIRED").length,resolved:records.filter(x=>x.status==="RESOLVED").length};
 const kinds=Array.from(new Set(records.map(x=>x.type)));
 const filtered=records.filter(x=>(tab==="all"||x.status===tab)&&(severity==="all"||x.severity===severity)&&(kind==="all"||x.type===kind)&&(assignee==="all"||x.assignedTo===assignee)&&(x.id+" "+x.title+" "+x.type+" "+x.description).toLowerCase().includes(query.toLowerCase()));
 const selected=records.find(x=>x.id===selectedId)||filtered[0];
 const pageRows=filtered.slice((page-1)*10,page*10),pages=Math.ceil(filtered.length/10)||1;
 const save=()=>{
   if(!canManage)return;
   if(modal==="create"){if(newTitle.trim().length<5||newDescription.trim().length<5)return;act({type:"PHASE2_INCIDENT_CREATE",title:newTitle,description:newDescription,kind:newType,severity:newSeverity,orderId:newOrder});setTab("all");setQuery("");toast("New simulated incident reported.");}
   else if(selected&&modal==="status"){if(reason.trim().length<3||targetStatus==="CLOSED"&&selected.status!=="RESOLVED")return;act({type:"PHASE2_INCIDENT_STATUS",id:selected.id,status:targetStatus,note:reason});toast("Incident status updated and logged.");}
   else if(selected&&modal==="note"){if(reason.trim().length<2)return;act({type:"PHASE2_INCIDENT_NOTE",id:selected.id,note:reason});toast("Private investigation note added.");}
   setModal(null);setReason("");setNewTitle("");setNewDescription("");setNewOrder("");
 };
 const changeAssign=(assignee:string)=>{if(selected&&canManage){act({type:"PHASE2_INCIDENT_ASSIGN",id:selected.id,assignedTo:assignee});toast("Incident assigned to "+assignee+".");}};
 const toOrder=()=>{if(selected?.relatedOrderId){sessionStorage.setItem("deetoo.demo.focusOrder",selected.relatedOrderId);navigate("orders");}else toast("No order is linked to this incident.");};
 const toRider=()=>{if(selected?.relatedRiderId){sessionStorage.setItem("deetoo.demo.focusRider",selected.relatedRiderId);navigate("riders");}else toast("No rider is linked to this incident.");};
 return <div className="dn-screen" data-testid="screen-incidents">
  <div className="dn-title-row"><div><h1>Incident Management</h1><p>Monitor, investigate and resolve operational, safety, payment and technical incidents.</p></div><button className="dn-btn primary" disabled={!canManage} onClick={()=>setModal("create")}><Plus size={16}/> Report Incident</button></div>
  <div className="dn-metrics five"><IconStat label="Open Incidents" value={counts.open} tone="red" icon={<AlertTriangle/>} foot="Waiting for triage"/><IconStat label="Investigating" value={counts.investigating} tone="amber" icon={<ShieldAlert/>} foot="Under investigation"/><IconStat label="Action Required" value={counts.action} tone="blue" icon={<UserRound/>} foot="Intervention needed"/><IconStat label="Resolved" value={counts.resolved} icon={<CheckCircle2/>} foot="Can be formally closed"/><IconStat label="Incidents (total)" value={records.length} tone="blue" icon={<Clock3/>} foot="Across all statuses"/></div>
  <div className="dn-incident-workspace">
   <div className="dn-incident-left">
    <Card className="dn-incident-register">
      <Tabs ariaLabel="Incident statuses" value={tab} onChange={setTab} tabs={[{key:"all",label:"All ("+records.length+")"},...statuses.map(status=>({key:status,label:status.replaceAll("_"," ")+" ("+records.filter(x=>x.status===status).length+")"}))]}/>
      <div className="dn-toolbar"><SearchBox placeholder="Search incidents..." value={query} onChange={setQuery}/><SelectBox label="Incident type" value={kind} onChange={setKind} options={[{value:"all",label:"All Types"},...kinds.map(x=>({value:x,label:x}))]}/><SelectBox label="Incident severity" value={severity} onChange={setSeverity} options={[{value:"all",label:"All Severity"},...["CRITICAL","HIGH","MEDIUM","LOW"].map(x=>({value:x,label:x}))]}/><SelectBox label="Assigned to" value={assignee} onChange={setAssignee} options={[{value:"all",label:"All Assignees"},...staff.map(x=>({value:x,label:x}))]}/></div>
      <div className="dn-table-scroll"><table className="dn-table dn-incident-table"><thead><tr><th>#</th><th>Type</th><th>Title & Description</th><th>Severity</th><th>Status</th><th>Assigned To</th><th>Created</th><th>Action</th></tr></thead><tbody>{pageRows.map(i=><tr key={i.id} className={selected?.id===i.id?"selected":""} tabIndex={0} onKeyDown={e=>e.key==="Enter"&&setSelectedId(i.id)} onClick={()=>{setSelectedId(i.id);setPanel("overview");}}><td><b>{i.id}</b></td><td>{i.type}</td><td><b>{i.title}</b><small>{i.description.slice(0,57)}...</small></td><td><Chip value={i.severity}/></td><td><Chip value={i.status}/></td><td>{i.assignedTo}</td><td>{displayTime(i.createdAt)}</td><td>⋮</td></tr>)}</tbody></table></div>{pageRows.length===0&&<Empty label="No incidents match these filters"/>}
      <div className="dn-pagination"><span>Showing {filtered.length?(page-1)*10+1:0}–{Math.min(page*10,filtered.length)} of {filtered.length} incidents</span><div><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>‹</button>{Array.from({length:Math.min(pages,6)},(_,i)=><button key={i} className={page===i+1?"selected":""} onClick={()=>setPage(i+1)}>{i+1}</button>)}<button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>›</button></div></div>
    </Card>
    <div className="dn-incident-analytics"><Card title="Incidents by Type"><Ring number={records.length} label="Total" parts={kinds.slice(0,4).map((x,i)=>({name:x,value:records.filter(r=>r.type===x).length,color:["#1478e1","#ff9e16","#0cb86c","#f64665"][i]}))}/></Card><Card title="Incidents by Status"><Ring number={records.length} label="Total" parts={["OPEN","INVESTIGATING","ACTION_REQUIRED","RESOLVED"].map((s,i)=>({name:s.replaceAll("_"," "),value:records.filter(x=>x.status===s).length,color:["#fa4966","#ffab20","#1478e1","#06a867"][i]}))}/></Card><Card title="Resolution by Category" desc="Illustrative demo counts"><Bars color="#17b36c" values={kinds.slice(0,7).map(x=>records.filter(r=>r.type===x&&["RESOLVED","CLOSED"].includes(r.status)).length)} labels={kinds.slice(0,7).map(x=>x.slice(0,5))}/></Card></div>
   </div>
   <Card className="dn-incident-detail">
    {selected?<><div className="dn-incident-title"><span className="dn-incident-alert"><AlertTriangle size={23}/></span><div><div><h2>{selected.id}</h2><Chip value={selected.severity}/><Chip value={selected.status}/></div><b>{selected.title}</b><p>{selected.description}</p></div></div>
      <Tabs ariaLabel="Incident details" value={panel} onChange={setPanel} tabs={[{key:"overview",label:"Overview"},{key:"investigation",label:"Investigation"},{key:"related",label:"Related Records"},{key:"media",label:"Media ("+selected.evidence.length+")"},{key:"audit",label:"Audit Log"}]}/>
      {panel==="overview"&&<><div className="dn-incident-safety"><AlertTriangle size={20}/><div><b>{selected.severity==="CRITICAL"?"Critical incident":selected.severity.toLowerCase()+" priority incident"}</b><small>Follow operational procedures and document follow-up actions.</small></div></div><div className="dn-incident-info"><div><h3>Incident Details</h3><DetailLine label="Type">{selected.type}</DetailLine><DetailLine label="Priority"><Chip value={selected.severity}/></DetailLine><DetailLine label="Status"><Chip value={selected.status}/></DetailLine><DetailLine label="Assigned to">{selected.assignedTo}</DetailLine><DetailLine label="Reported by">{selected.reporter}</DetailLine><DetailLine label="Created">{displayTime(selected.createdAt)}</DetailLine><DetailLine label="Location">{selected.location}</DetailLine><p>{selected.description}</p></div><div><h3>Investigation Timeline</h3><div className="dn-timeline">{selected.timeline.map((t,i)=><div key={i}><span className="dn-time-point">●</span><div><strong>{t.event}</strong><small>{displayTime(t.at)} · {t.actor}</small><p>{t.note}</p></div></div>)}</div></div></div></>}
      {panel==="investigation"&&<div className="dn-panel-information"><h3>Investigation Notes</h3>{selected.notes.length?selected.notes.map((n,i)=><p className="dn-note-block" key={i}>{n}</p>):<Empty label="No private investigation notes"/>}<button className="dn-btn primary" disabled={!canManage} onClick={()=>setModal("note")}>Add Internal Note</button></div>}
      {panel==="related"&&<div className="dn-incident-related"><Card title="Related Order">{selected.relatedOrderId?<><b>#{selected.relatedOrderId}</b><p>Open the order's detail view</p><button className="dn-btn outline" onClick={toOrder}>View Order <ArrowRight size={13}/></button></>:<Empty label="No linked order"/>}</Card><Card title="Related Rider">{selected.relatedRiderId?<><b>#{selected.relatedRiderId}</b><p>Review rider record and assignments</p><button className="dn-btn outline" onClick={toRider}>View Rider <ArrowRight size={13}/></button></>:<Empty label="No linked rider"/>}</Card></div>}
      {panel==="media"&&<div className="dn-panel-information"><h3>Evidence & Attachments</h3>{selected.evidence.map((item,i)=><p className="dn-note-block" key={i}>📎 {item.name} · {item.type} · illustrative placeholder</p>)}{!selected.evidence.length&&<Empty label="No evidence attached"/>}<p>Actual file storage, upload scanning and access control are reserved for backend integration.</p></div>}
      {panel==="audit"&&<div className="dn-timeline">{selected.timeline.map((t,i)=><div key={i}><span className="dn-time-point">●</span><div><strong>{t.event}</strong><small>{displayTime(t.at)} · {t.actor}</small><p>{t.note}</p></div></div>)}</div>}
      <div className="dn-incident-linked"><h3>Related Records</h3><div className="dn-incident-related"><button onClick={toOrder}><b>Order</b><span>{selected.relatedOrderId?"#"+selected.relatedOrderId:"Not linked"}</span><ArrowRight size={13}/></button><button onClick={toRider}><b>Rider</b><span>{selected.relatedRiderId||"Not linked"}</span><ArrowRight size={13}/></button></div></div>
      <div className="dn-incident-actions"><SelectBox label="Assign investigator" value={selected.assignedTo} onChange={changeAssign} options={staff.map(x=>({value:x,label:x}))}/><button className="dn-btn outline" disabled={!canManage} onClick={()=>{setTargetStatus(selected.status);setReason("");setModal("status");}}>Change Status</button><button className="dn-btn outline" disabled={!canManage} onClick={()=>{setReason("");setModal("note");}}>Add Internal Note</button><button className="dn-btn outline" onClick={()=>navigate("support")}><MessageSquare size={14}/> Support</button><button className="dn-btn red" disabled={!canManage} onClick={()=>{setTargetStatus("ACTION_REQUIRED");setReason("");setModal("status");}}>Escalate</button></div>
    </>:<Empty label="Select an incident to investigate"/>}
   </Card>
  </div>
  {modal==="create"&&<Modal title="Report new incident" subtitle="Opens a simulated investigation record" onClose={()=>setModal(null)} onConfirm={save} disabled={!canManage||newTitle.trim().length<5||newDescription.trim().length<5} confirmText="Report incident"><label className="dn-field">Incident title<input value={newTitle} onChange={e=>setNewTitle(e.target.value)} placeholder="What happened?"/></label><label className="dn-field">Incident category<select value={newType} onChange={e=>setNewType(e.target.value)}>{kinds.map(x=><option key={x}>{x}</option>)}</select></label><label className="dn-field">Severity<select value={newSeverity} onChange={e=>setNewSeverity(e.target.value as Severity)}>{["LOW","MEDIUM","HIGH","CRITICAL"].map(x=><option key={x}>{x}</option>)}</select></label><label className="dn-field">Related order (optional)<select value={newOrder} onChange={e=>setNewOrder(e.target.value)}><option value="">Not linked</option>{data.orders.slice(0,45).map(x=><option key={x.id} value={x.id}>{x.id}</option>)}</select></label><label className="dn-field">Description<textarea value={newDescription} onChange={e=>setNewDescription(e.target.value)} placeholder="Investigation context"/></label></Modal>}
  {modal==="status"&&selected&&<Modal title="Update incident lifecycle" subtitle={selected.id+" · "+selected.title} onClose={()=>setModal(null)} onConfirm={save} disabled={!canManage||reason.trim().length<3||(targetStatus==="CLOSED"&&selected.status!=="RESOLVED")} confirmText="Save status"><label className="dn-field">Status<select value={targetStatus} onChange={e=>setTargetStatus(e.target.value as IncidentStatus)}>{statuses.map(s=><option value={s} key={s}>{s.replaceAll("_"," ")}</option>)}</select></label><label className="dn-field">Required investigation note<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Document the action and outcome"/></label>{targetStatus==="CLOSED"&&selected.status!=="RESOLVED"&&<p>A case must be resolved before it can be closed.</p>}</Modal>}
  {modal==="note"&&selected&&<Modal title="Private incident note" subtitle={selected.id} onClose={()=>setModal(null)} onConfirm={save} disabled={!canManage||reason.trim().length<2} confirmText="Save internal note"><label className="dn-field">Investigation note<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Visible only to internal admins in this demo"/></label></Modal>}
 </div>;
}
