import React,{useEffect,useState} from "react";
import {ArrowRight, Ban, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, Clock3, Download, Edit3, FileCheck2, Filter, MapPin, Plus, ShieldCheck, Store, StoreIcon, TrendingUp, Users} from "lucide-react";
import {displayTime,formatMoney,orderTotal} from "../data";
import type {MerchantRecord} from "../phase2Data";
import {useDemo,canAct} from "../store";
import {Bars,Card,Chip,DetailLine,Empty,IconStat,Initials,Modal,Ring,SearchBox,SelectBox,Tabs} from "../ui";
const categories=["Restaurant","Supermarket","Café","Pharmacy","Other"];
const counties=["Nairobi","Kiambu","Mombasa","Nakuru","Kisumu","Machakos"];
export function MerchantsScreen({navigate,county,globalSearch,toast}:{navigate:(s:string)=>void;county:string;globalSearch:string;toast:(s:string)=>void}){
 const {data,act,role}=useDemo(),all=data.phase2.merchants,canManage=canAct(role,"merchant");
 const [tab,setTab]=useState("all"),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[category,setCategory]=useState("all"),[localCounty,setLocalCounty]=useState("all"),[selectedId,setSelectedId]=useState<string|null>(null),[detail,setDetail]=useState("overview"),[page,setPage]=useState(1);
 const [modal,setModal]=useState<"create"|"edit"|"review"|"branch"|null>(null),[nextStatus,setNextStatus]=useState<MerchantRecord["status"]>("ACTIVE"),[reason,setReason]=useState(""),[form,setForm]=useState({name:"",category:"Restaurant",owner:"",email:"",phone:""}),[branchForm,setBranchForm]=useState({name:"",county:"Nairobi",area:"Westlands",address:""});
 useEffect(()=>{if(globalSearch)setSearch(globalSearch);},[globalSearch]);
 useEffect(()=>setPage(1),[tab,search,status,category,localCounty,county]);
 const filtered=all.filter(m=>(tab==="all"||tab==="branches"||tab==="performance"||tab==="approvals"&&m.status==="PENDING"||tab==="onboarding"&&m.status==="ONBOARDING"||tab==="active"&&m.status==="ACTIVE"||tab==="suspended"&&m.status==="SUSPENDED")&&(status==="all"||m.status===status)&&(category==="all"||m.category===category)&&(localCounty==="all"||m.branches.some(b=>b.county===localCounty))&&(county==="all"||m.branches.some(b=>b.county===county))&&(m.name+" "+m.id+" "+m.owner+" "+m.email).toLowerCase().includes(search.toLowerCase()));
 const shown=filtered.slice((page-1)*9,page*9),pages=Math.ceil(filtered.length/9)||1;
 const selected=shown.find(m=>m.id===selectedId)||shown[0];
 const merchantOrders=selected?data.orders.filter(o=>o.merchant===selected.name):[];
 const branches=all.reduce((a,m)=>a+m.branches.length,0),active=all.filter(m=>m.status==="ACTIVE").length,pending=all.filter(m=>m.status==="PENDING").length,suspended=all.filter(m=>m.status==="SUSPENDED").length;
 const openCreate=()=>{setForm({name:"",category:"Restaurant",owner:"",email:"",phone:""});setModal("create");};
 const openEdit=()=>{if(!selected)return;setForm({name:selected.name,category:selected.category,owner:selected.owner,email:selected.email,phone:selected.phone});setModal("edit");};
 const save=()=>{
  if(!canManage)return;
  if(modal==="create"){if(form.name.trim().length<3||!form.email.includes("@"))return;act({type:"PHASE2_MERCHANT_CREATE",...form});setTab("onboarding");toast("New merchant added to onboarding.");}
  if(modal==="edit"&&selected){if(form.name.trim().length<3||!form.email.includes("@"))return;act({type:"PHASE2_MERCHANT_EDIT",id:selected.id,...form});toast("Merchant details saved across the demo.");}
  if(modal==="review"&&selected){if(reason.trim().length<3)return;act({type:"PHASE2_MERCHANT_STATUS",id:selected.id,status:nextStatus,note:reason});toast("Merchant status and verification updated.");}
  if(modal==="branch"&&selected){if(branchForm.name.trim().length<3||branchForm.area.trim().length<2)return;act({type:"PHASE2_MERCHANT_BRANCH",id:selected.id,...branchForm});toast("Branch added to the merchant profile.");}
  setModal(null);setReason("");if(modal==="create")setSelectedId(null);
 };
 const exportResults=()=>{const csv=["ID,Merchant,Category,Status,Verification,Branches",...filtered.map(x=>[x.id,x.name,x.category,x.status,x.verification,String(x.branches.length)].map(s=>'"'+s.replaceAll('"','""')+'"').join(","))].join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="deetoo-demo-merchants.csv";a.click();URL.revokeObjectURL(url);toast("Merchant records exported.");};
 const toOrders=()=>{if(merchantOrders.length){sessionStorage.setItem("deetoo.demo.focusOrder",merchantOrders[0].id);navigate("orders");}else toast("This merchant has no seeded orders.");};
 return <div className="dn-screen" data-testid="screen-merchants">
  <div className="dn-title-row"><div><h1>Merchant Management</h1><p>Manage merchant onboarding, approvals, branches and operational status.</p></div><div className="dn-title-buttons"><button className="dn-btn outline" onClick={exportResults}><Download size={15}/> Export</button><button className="dn-btn primary" disabled={!canManage} onClick={openCreate}><Plus size={16}/> Add Merchant</button></div></div>
  <div className="dn-metrics six">
   <IconStat label="Total Merchants" value={all.length} change="In demo directory" icon={<Users/>}/>
   <IconStat label="Pending Approvals" value={pending} tone="amber" icon={<Clock3/>}/>
   <IconStat label="Active Merchants" value={active} icon={<CheckCircle2/>}/>
   <IconStat label="Suspended" value={suspended} tone="red" icon={<Ban/>}/>
   <IconStat label="Total Branches" value={branches} tone="blue" icon={<Store/>}/>
   <IconStat label="Verification Rate" value={Math.round(all.filter(m=>m.verification==="VERIFIED").length/all.length*100)+"%"} icon={<ShieldCheck/>}/>
  </div>
  <Tabs value={tab} onChange={setTab} ariaLabel="Merchant sections" tabs={[{key:"all",label:"All Merchants ("+all.length+")"},{key:"approvals",label:"Pending Approvals ("+pending+")"},{key:"active",label:"Active ("+active+")"},{key:"suspended",label:"Suspended ("+suspended+")"},{key:"onboarding",label:"Onboarding ("+all.filter(m=>m.status==="ONBOARDING").length+")"},{key:"branches",label:"Branches"},{key:"performance",label:"Performance"}]}/>
  <div className="dn-merchant-workspace">
   <Card className="dn-merchant-directory">
    <div className="dn-toolbar"><SearchBox placeholder="Search merchants..." value={search} onChange={setSearch}/><SelectBox label="Merchant status" value={status} onChange={setStatus} options={[{value:"all",label:"All Statuses"},...["ACTIVE","PENDING","ONBOARDING","SUSPENDED"].map(x=>({value:x,label:x}))]}/><SelectBox label="Merchant category" value={category} onChange={setCategory} options={[{value:"all",label:"All Categories"},...categories.map(x=>({value:x,label:x}))]}/><SelectBox label="Merchant county" value={localCounty} onChange={setLocalCounty} options={[{value:"all",label:"All Counties"},...counties.map(x=>({value:x,label:x}))]}/></div>
    <div className="dn-table-scroll"><table className="dn-table dn-merchant-table"><thead><tr><th>Merchant</th><th>Category</th><th>Branches</th><th>Status</th><th>Verified</th><th>Joined</th><th>Rating</th></tr></thead><tbody>{shown.map(m=><tr key={m.id} tabIndex={0} className={selected?.id===m.id?"selected":""} onClick={()=>{setSelectedId(m.id);setDetail(tab==="branches"?"branches":"overview");}} onKeyDown={e=>e.key==="Enter"&&setSelectedId(m.id)}><td><div className="dn-cell-person"><Initials name={m.name}/><div><b>{m.name}</b><small>{m.branches[0]?.area||"No branches"}</small></div></div></td><td>{m.category}</td><td>{m.branches.length}</td><td><Chip value={m.status}/></td><td><Chip value={m.verification}/></td><td>{displayTime(m.joinedAt)}</td><td className="dn-rating">{m.rating?"★ "+m.rating.toFixed(1):"—"}</td></tr>)}</tbody></table></div>{!shown.length&&<Empty label="No merchants match the current filters"/>}
    <div className="dn-pagination"><span>Showing {filtered.length?(page-1)*9+1:0}–{Math.min(page*9,filtered.length)} of {filtered.length} merchants</span><div><button disabled={page===1} onClick={()=>setPage(v=>v-1)}>‹</button>{Array.from({length:Math.min(5,pages)},(_,i)=><button key={i} className={page===i+1?"selected":""} onClick={()=>setPage(i+1)}>{i+1}</button>)}<button disabled={page>=pages} onClick={()=>setPage(v=>v+1)}>›</button></div></div>
   </Card>
   <Card className="dn-merchant-detail">
    {selected?<><div className="dn-merchant-top"><Initials name={selected.name}/><div><h2>{selected.name}</h2><Chip value={selected.status}/><p>{selected.category} · {selected.branches.length} branches</p><p>{selected.branches[0]?.area||"Awaiting branch setup"}, {selected.branches[0]?.county||"Kenya"} · <span className="dn-rating">★ {selected.rating?selected.rating.toFixed(1):"New"}</span></p></div><button className="dn-btn outline" onClick={openEdit} disabled={!canManage}><Edit3 size={14}/> Edit</button></div>
     <Tabs ariaLabel="Merchant details" value={detail} onChange={setDetail} tabs={[{key:"overview",label:"Overview"},{key:"branches",label:"Branches ("+selected.branches.length+")"},{key:"documents",label:"Documents"},{key:"performance",label:"Performance"},{key:"payouts",label:"Payouts"},{key:"settings",label:"Settings"}]}/>
     {detail==="overview"&&<div className="dn-merchant-info-grid"><div className="dn-innerbox"><div className="dn-card-subhead">Business Information</div><DetailLine label="Business Name">{selected.name}</DetailLine><DetailLine label="Category">{selected.category}</DetailLine><DetailLine label="Email">{selected.email}</DetailLine><DetailLine label="Phone">{selected.phone}</DetailLine><DetailLine label="Registration">{selected.registration}</DetailLine><DetailLine label="Joined">{displayTime(selected.joinedAt)}</DetailLine><DetailLine label="Status"><Chip value={selected.status}/></DetailLine><DetailLine label="Verification"><Chip value={selected.verification}/></DetailLine><p>{selected.description}</p></div>
     <div className="dn-innerbox"><div className="dn-card-subhead">Owner / Contact Person</div><div className="dn-cell-person"><Initials name={selected.owner}/><b>{selected.owner}</b></div><p>{selected.email}</p><p>{selected.phone}</p><div className="dn-card-subhead">Performance (sample orders)</div><DetailLine label="Orders in demo">{merchantOrders.length}</DetailLine><DetailLine label="Gross order value">{formatMoney(merchantOrders.reduce((a,o)=>a+orderTotal(o),0))}</DetailLine><DetailLine label="Average rating">★ {selected.rating.toFixed(1)}</DetailLine><Bars values={[5,9,7,10,6,8,10,7,9,11,9,8]} labels={["1","","","","7","","","","14","","","28"]}/></div></div>}
     {detail==="branches"&&<div className="dn-panel-information"><div className="dn-inline-heading"><h3>Merchant Branches ({selected.branches.length})</h3><button className="dn-btn primary" disabled={!canManage} onClick={()=>setModal("branch")}><Plus size={14}/> Add Branch</button></div><div className="dn-table-scroll"><table className="dn-table"><thead><tr><th>Branch</th><th>County</th><th>Area</th><th>Address</th><th>Status</th><th>Action</th></tr></thead><tbody>{selected.branches.map(b=><tr key={b.id}><td><b>{b.name}</b></td><td>{b.county}</td><td>{b.area}</td><td>{b.address}</td><td><Chip value={b.status}/></td><td><button className="dn-smalloutline" disabled={!canManage} onClick={()=>{act({type:"PHASE2_MERCHANT_BRANCH_STATUS",id:selected.id,branchId:b.id,status:b.status==="ACTIVE"?"PAUSED":"ACTIVE"});toast("Branch updated.");}}>{b.status==="ACTIVE"?"Pause":"Resume"}</button></td></tr>)}</tbody></table></div>{!selected.branches.length&&<Empty label="Merchant has no branches yet"/>}</div>}
     {detail==="documents"&&<div className="dn-panel-information"><DetailLine label="Verification status"><Chip value={selected.verification}/></DetailLine><DetailLine label="Business registration">{selected.registration}</DetailLine><p>Mock compliance state only. No real merchant documents have been uploaded or verified.</p><button className="dn-btn outline" onClick={()=>{setNextStatus("PENDING");setModal("review");}} disabled={!canManage}>Request verification review</button></div>}
     {detail==="performance"&&<div className="dn-panel-information"><DetailLine label="Completed orders">{merchantOrders.filter(o=>o.status==="DELIVERED").length}</DetailLine><DetailLine label="Demo gross sales">{formatMoney(merchantOrders.reduce((a,o)=>a+orderTotal(o),0))}</DetailLine><DetailLine label="Average rating">{selected.rating.toFixed(1)}</DetailLine><Bars values={[8,11,7,14,12,9,17,14,10,16,13,15]} labels={["1","","","","7","","","","14","","","28"]}/><button className="dn-btn outline" onClick={toOrders}>View merchant orders <ArrowRight size={13}/></button></div>}
     {detail==="payouts"&&<div className="dn-panel-information"><Empty label="Payout workflow begins in Phase 3" detail="The approved UI remains visible and will be connected to the same merchant profile." /></div>}
     {detail==="settings"&&<div className="dn-panel-information"><DetailLine label="Merchant status"><Chip value={selected.status}/></DetailLine><DetailLine label="Verification"><Chip value={selected.verification}/></DetailLine><button className="dn-btn outline" onClick={()=>{setNextStatus(selected.status==="SUSPENDED"?"ACTIVE":"SUSPENDED");setReason("");setModal("review");}} disabled={!canManage}>{selected.status==="SUSPENDED"?"Reactivate":"Suspend"} merchant</button></div>}
     <div className="dn-merchant-actions"><button className="dn-btn outline" onClick={()=>setDetail("branches")}>View Branches</button><button className="dn-btn outline" onClick={toOrders}>View Orders</button>{canManage&&selected.status!=="ACTIVE"&&<button className="dn-btn primary" onClick={()=>{setNextStatus("ACTIVE");setReason("");setModal("review");}}><CheckCircle2 size={13}/> Approve Merchant</button>}{canManage&&selected.status==="ACTIVE"&&<button className="dn-btn red" onClick={()=>{setNextStatus("SUSPENDED");setReason("");setModal("review");}}>Suspend</button>}</div>
    </>:<Empty label="Choose a merchant from the directory"/>}
   </Card>
  </div>
  <div className="dn-merchant-bottom"><Card title="Merchants by Status"><Ring number={all.length} label="Total" parts={["ACTIVE","PENDING","SUSPENDED","ONBOARDING"].map((s,i)=>({name:s,value:all.filter(m=>m.status===s).length,color:["#05aa66","#ffb21d","#fd4b64","#3482ea"][i]}))}/></Card><Card title="Merchants by Category"><Ring number={all.length} label="Total" parts={categories.slice(0,4).map((s,i)=>({name:s,value:all.filter(m=>m.category===s).length,color:["#096ff2","#ff9b20","#0db56f","#a985ed"][i]}))}/></Card><Card title="Top Performing Merchants"><div className="dn-simple-ranking">{all.filter(m=>m.status==="ACTIVE").sort((a,b)=>b.rating-a.rating).slice(0,5).map((m,i)=><button key={m.id} onClick={()=>{setSelectedId(m.id);setDetail("performance");}}><span>{i+1}</span><Initials name={m.name}/><b>{m.name}</b><span>★ {m.rating.toFixed(1)}</span></button>)}</div></Card><Card title="Recent Activity"><div className="dn-simple-activity">{data.phase2.actions.filter(x=>x.action.includes("Merchant")).slice(0,5).map((x,i)=><p key={i}>{x.action} · {x.detail}</p>)}{!data.phase2.actions.some(x=>x.action.includes("Merchant"))&&<p>New branches, approvals and edits will appear here.</p>}</div></Card></div>
  {modal==="create"&&<Modal title="Add merchant" subtitle="Starts a frontend-only merchant onboarding record" onClose={()=>setModal(null)} onConfirm={save} disabled={!canManage||form.name.trim().length<3||!form.email.includes("@")} confirmText="Create merchant"><label className="dn-field">Business name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="dn-field">Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="dn-field">Owner<input value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}/></label><label className="dn-field">Email<input value={form.email} type="email" onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="dn-field">Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label></Modal>}
  {modal==="edit"&&selected&&<Modal title="Edit merchant details" subtitle={selected.id+" · changes remain in the demo"} onClose={()=>setModal(null)} onConfirm={save} disabled={!canManage||form.name.trim().length<3||!form.email.includes("@")} confirmText="Save merchant">{(["name","owner","email","phone"] as const).map(field=><label className="dn-field" key={field}>{field[0].toUpperCase()+field.slice(1)}<input value={form[field]} onChange={e=>setForm({...form,[field]:e.target.value})}/></label>)}<label className="dn-field">Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label></Modal>}
  {modal==="review"&&selected&&<Modal title="Merchant approval / restriction" subtitle={selected.name} onClose={()=>setModal(null)} onConfirm={save} danger={nextStatus==="SUSPENDED"} confirmText="Confirm merchant action" disabled={!canManage||reason.trim().length<3}><label className="dn-field">New operational status<select value={nextStatus} onChange={e=>setNextStatus(e.target.value as MerchantRecord["status"])}>{["ACTIVE","PENDING","ONBOARDING","SUSPENDED"].map(x=><option value={x} key={x}>{x}</option>)}</select></label><label className="dn-field">Required audit note<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain why this status is appropriate"/></label></Modal>}
  {modal==="branch"&&selected&&<Modal title="Add merchant branch" subtitle={selected.name+" · new location"} onClose={()=>setModal(null)} onConfirm={save} disabled={!canManage||branchForm.name.trim().length<3||branchForm.area.trim().length<2} confirmText="Save branch"><label className="dn-field">Branch name<input value={branchForm.name} onChange={e=>setBranchForm({...branchForm,name:e.target.value})}/></label><label className="dn-field">County<select value={branchForm.county} onChange={e=>setBranchForm({...branchForm,county:e.target.value})}>{counties.map(x=><option key={x}>{x}</option>)}</select></label><label className="dn-field">Area<input value={branchForm.area} onChange={e=>setBranchForm({...branchForm,area:e.target.value})}/></label><label className="dn-field">Address<input value={branchForm.address} onChange={e=>setBranchForm({...branchForm,address:e.target.value})}/></label></Modal>}
 </div>;
}
