import React,{useEffect,useMemo,useState} from "react";
import {AlertTriangle, ArrowRight, Bike, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Download, Edit3, FileText, Filter, MapPin, MessageSquare, MoreHorizontal, Phone, Printer, Search, ShoppingCart, Truck, UserRound, XCircle} from "lucide-react";
import {Order,OrderStatus,formatMoney,orderTotal,isActive,displayTime} from "../data";
import {useDemo,canAct} from "../store";
import {Card,Chip,DemoMap,DetailLine,Empty,IconStat,Initials,Journey,Modal,SearchBox,SelectBox,Tabs} from "../ui";
export function OrdersScreen({county,navigate,globalSearch,toast}:{county:string;navigate:(id:string)=>void;globalSearch:string;toast:(s:string)=>void}){
 const {data,act,role}=useDemo();
 const [tab,setTab]=useState("all"),[search,setSearch]=useState(""),[sort,setSort]=useState("newest"),[selectedId,setSelectedId]=useState<string|null>(null);
 const [page,setPage]=useState(1),[details,setDetails]=useState("overview"),[note,setNote]=useState(""),[cancelReason,setCancelReason]=useState(""),[modal,setModal]=useState<"cancel"|"status"|"note"|null>(null),[newStatus,setNewStatus]=useState<OrderStatus>("PREPARING");
 useEffect(()=>{if(globalSearch)setSearch(globalSearch);},[globalSearch]);
 useEffect(()=>setPage(1),[tab,search,sort,county]);
 const countyOrders=data.orders.filter(o=>county==="all"||o.pickup.county===county);
 const statuses={all:countyOrders.length,progress:countyOrders.filter(o=>isActive(o)&&o.status!=="DELAYED").length,completed:countyOrders.filter(o=>o.status==="DELIVERED").length,delayed:countyOrders.filter(o=>o.status==="DELAYED").length,cancelled:countyOrders.filter(o=>o.status==="CANCELLED").length};
 const matching=countyOrders.filter(o=>(tab==="all"||tab==="progress"&&isActive(o)&&o.status!=="DELAYED"||tab==="completed"&&o.status==="DELIVERED"||tab==="delayed"&&o.status==="DELAYED"||tab==="cancelled"&&o.status==="CANCELLED")&&(o.id+" "+o.merchant+" "+o.customer+" "+o.area+" "+o.destination.name).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==="oldest"?a.createdAt.localeCompare(b.createdAt):b.createdAt.localeCompare(a.createdAt));
 const totalPages=Math.ceil(matching.length/12)||1;
 const showing=matching.slice((page-1)*12,page*12);
 const selected=countyOrders.find(o=>o.id===selectedId)||showing[0];
 const rider=selected?data.riders.find(r=>r.id===selected.riderId):undefined;
 const canManage=canAct(role,"order");
 const focusDispatch=()=>{if(selected){sessionStorage.setItem("deetoo.demo.focusOrder",selected.id);}navigate("dispatch");};
 const doAction=()=>{
  if(!selected||!canManage)return;
  if(modal==="cancel"&&cancelReason.trim().length>=3){act({type:"CANCEL_ORDER",orderId:selected.id,reason:cancelReason});toast("Order #"+selected.id+" cancelled in the demo.");}
  if(modal==="note"&&note.trim().length>=2){act({type:"ADD_NOTE",orderId:selected.id,note});toast("Internal order note added.");}
  if(modal==="status"){act({type:"UPDATE_ORDER",orderId:selected.id,status:newStatus,reason:"Changed using Orders & Deliveries demo"});toast("Order updated to "+newStatus.replaceAll("_"," ").toLowerCase());}
  setModal(null);setNote("");setCancelReason("");
 };
 const allowedStatuses:OrderStatus[]=selected?.riderId?["RIDER_ASSIGNED","PICKED_UP","IN_TRANSIT","DELIVERED","DELAYED"]:["PREPARING","DELAYED"];
 function exportRows(){const rows=[["Order","Merchant","Customer","Status","Total"],...matching.map(o=>[o.id,o.merchant,o.customer,o.status,String(orderTotal(o))])];const body=rows.map(r=>r.map(s=>'"'+String(s).replaceAll('"','""')+'"').join(",")).join("\n");const url=URL.createObjectURL(new Blob([body],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="deetoo-demo-orders.csv";a.click();URL.revokeObjectURL(url);toast("Visible order results exported.");}
 return <div className="dn-screen" data-testid="screen-orders">
  <div className="dn-title-row"><div><h1>Orders & Deliveries</h1><p>Manage and track all orders from placement to delivery.</p></div><div className="dn-inline-kpis"><IconStat label="Total Orders" value={statuses.all} icon={<ShoppingCart/>}/><IconStat label="Completed" value={statuses.completed} icon={<CheckCircle2/>}/><IconStat label="Delayed" value={statuses.delayed} tone="red" icon={<AlertTriangle/>}/><IconStat label="Cancelled" value={statuses.cancelled} tone="grey" icon={<XCircle/>}/></div></div>
  <div className="dn-orders-layout">
   <Card className="dn-orders-list">
    <Tabs value={tab} onChange={setTab} ariaLabel="Order statuses" tabs={[{key:"all",label:"All Orders ("+statuses.all+")"},{key:"progress",label:"In Progress ("+statuses.progress+")"},{key:"completed",label:"Completed ("+statuses.completed+")"},{key:"delayed",label:"Delayed ("+statuses.delayed+")"},{key:"cancelled",label:"Cancelled ("+statuses.cancelled+")"}]}/>
    <div className="dn-toolbar"><SearchBox placeholder="Search orders..." value={search} onChange={setSearch}/><button className="dn-iconbutton" aria-label="Clear order filters" onClick={()=>{setTab("all");setSearch("");}}><Filter size={15}/></button><SelectBox label="Sort orders" value={sort} onChange={setSort} options={[{value:"newest",label:"Newest first"},{value:"oldest",label:"Oldest first"}]}/></div>
    <div className="dn-order-directory">
      {showing.map(o=><button key={o.id} onClick={()=>{setSelectedId(o.id);setDetails("overview");}} className={"dn-order-line "+(selected?.id===o.id?"selected":"")}><span className="dn-order-check">□</span><div className="dn-order-id"><b>#{o.id}</b><small>{displayTime(o.createdAt)}</small></div><div className="dn-order-merchant"><span className="dn-merchant-mark">{o.merchant[0]}</span><div><b>{o.merchant}</b><small>{o.area}</small></div></div><Chip value={o.status}/><b className="dn-order-total">{formatMoney(orderTotal(o))}</b><ChevronRight size={15}/></button>)}
      {showing.length===0&&<Empty/>}
    </div>
    <footer className="dn-pagination"><span>Showing {matching.length?(page-1)*12+1:0}–{Math.min(page*12,matching.length)} of {matching.length} orders</span><div><button aria-label="Previous page" disabled={page===1} onClick={()=>setPage(x=>x-1)}><ChevronLeft size={15}/></button>{Array.from({length:Math.min(totalPages,5)},(_,i)=><button key={i} aria-label={"Page "+(i+1)} className={page===i+1?"selected":""} onClick={()=>setPage(i+1)}>{i+1}</button>)}<button aria-label="Next page" disabled={page>=totalPages} onClick={()=>setPage(x=>x+1)}><ChevronRight size={15}/></button></div></footer>
   </Card>
   <div className="dn-order-main">
    <Card className="dn-order-detail">
     {selected?<><div className="dn-order-detail-head"><div><div><h2>#{selected.id}</h2><Chip value={selected.status}/></div><p>Placed {displayTime(selected.createdAt)} · Estimated delivery {selected.etaMinutes} mins (demo)</p></div><div className="dn-detail-actions"><button className="dn-btn outline" onClick={()=>window.print()}><Printer size={14}/> Print</button><button className="dn-btn outline" onClick={exportRows}><Download size={14}/> Export</button><button className="dn-btn primary" disabled={!canManage||!isActive(selected)} onClick={()=>{setNewStatus(selected.status==="DELAYED"?"PREPARING":selected.status);setModal("status");}}><Edit3 size={14}/> Edit Order</button></div></div>
      <Tabs ariaLabel="Order detail sections" value={details} onChange={setDetails} tabs={[{key:"overview",label:"Overview"},{key:"items",label:"Items ("+selected.items.length+")"},{key:"timeline",label:"Timeline"},{key:"customer",label:"Customer"},{key:"merchant",label:"Merchant"},{key:"rider",label:"Rider"},{key:"payments",label:"Payments"},{key:"notes",label:"Notes & Support"}]}/>
      {details==="overview"&&<><div className="dn-order-middle">
       <div className="dn-order-timeline"><div className="dn-card-subhead"><b>Delivery Timeline</b><span className="dn-live-indicator">● Demo</span></div><div className="dn-long-journey">{["Order Placed","Merchant Accepted","Preparing","Rider Assigned","Picked Up","Out for Delivery","Delivered"].map((label,i)=>{const done=selected.status==="DELIVERED" || selected.status!=="CANCELLED"&&i<=({"PREPARING":2,"RIDER_ASSIGNED":3,"PICKED_UP":4,"IN_TRANSIT":5,"DELAYED":selected.riderId?3:2} as Record<string,number>)[selected.status];const found=selected.history.find(e=>e.event.toLowerCase()===label.toLowerCase());return <div key={label} className={done?"done":""}><span>●</span><div><b>{label}</b><small>{found?displayTime(found.at):done?"Completed in demo":"Pending"}</small></div></div>;})}</div></div>
       <DemoMap height={375} orders={[selected]} riders={rider?[rider]:[]} onSelectOrder={()=>{}}/>
       <div className="dn-order-contacts"><div><span>Customer</span><div className="dn-contact-head"><Initials name={selected.customer}/><div><b>{selected.customer}</b><small>{selected.customerPhone}</small></div></div><p>{selected.destination.name}, {selected.destination.county}</p><button className="dn-smalloutline" onClick={()=>setDetails("customer")}>View Customer</button></div><div><span>Merchant</span><div className="dn-contact-head"><Initials name={selected.merchant}/><div><b>{selected.merchant}</b><small>{selected.area}, Nairobi</small></div></div><button className="dn-smalloutline" onClick={()=>setDetails("merchant")}>View Merchant</button></div><div><span>Rider</span><div className="dn-contact-head"><Initials name={rider?.name||"?"}/><div><b>{rider?.name||"Not Assigned"}</b><small>{rider?.vehicle||"This order needs a rider"}</small></div></div><button className="dn-mini-primary" onClick={focusDispatch}>{rider?"View Dispatch":"Assign Rider"}</button></div></div>
      </div><div className="dn-order-summary-row"><div><div className="dn-card-subhead"><b>Order Items ({selected.items.length})</b></div>{selected.items.map((item,i)=><DetailLine key={i} label={item.name+" ×"+item.qty}>{formatMoney(item.qty*item.price)}</DetailLine>)}</div><div><div className="dn-card-subhead"><b>Order Summary</b></div><DetailLine label="Items Subtotal">{formatMoney(selected.subtotal)}</DetailLine><DetailLine label="Delivery Fee">{formatMoney(selected.deliveryFee)}</DetailLine><DetailLine label="Service Fee">{formatMoney(selected.serviceFee)}</DetailLine><DetailLine label="Total">{formatMoney(orderTotal(selected))}</DetailLine></div><div><div className="dn-card-subhead"><b>Payment Details</b></div><DetailLine label="Method">{selected.paymentMethod}</DetailLine><DetailLine label="Status"><Chip value={selected.paymentStatus}/></DetailLine><DetailLine label="Amount">{formatMoney(orderTotal(selected))}</DetailLine><button className="dn-smalloutline" onClick={()=>setDetails("payments")}>View Payment Details</button></div></div></>}
      {details==="items"&&<div className="dn-panel-information">{selected.items.map((item,i)=><DetailLine key={i} label={item.name+" ×"+item.qty}>{formatMoney(item.qty*item.price)}</DetailLine>)}<DetailLine label="Items subtotal">{formatMoney(selected.subtotal)}</DetailLine></div>}
      {details==="timeline"&&<div className="dn-timeline">{selected.history.map((e,i)=><div key={i}><span className="dn-time-point">●</span><div><strong>{e.event}</strong><small>{displayTime(e.at)} · {e.by}</small><p>{e.detail}</p></div></div>)}</div>}
      {details==="customer"&&<div className="dn-panel-information"><DetailLine label="Customer">{selected.customer}</DetailLine><DetailLine label="Phone">{selected.customerPhone}</DetailLine><DetailLine label="Drop-off area">{selected.destination.name}</DetailLine><DetailLine label="County">{selected.destination.county}</DetailLine></div>}
      {details==="merchant"&&<div className="dn-panel-information"><DetailLine label="Merchant">{selected.merchant}</DetailLine><DetailLine label="Branch">{selected.area}</DetailLine><DetailLine label="County">{selected.pickup.county}</DetailLine></div>}
      {details==="rider"&&<div className="dn-panel-information"><DetailLine label="Rider">{rider?.name||"Not assigned"}</DetailLine><DetailLine label="Status"><Chip value={rider?.status}/></DetailLine><DetailLine label="Vehicle">{rider?.vehicle||"—"}</DetailLine><button className="dn-btn primary" onClick={focusDispatch}>Open dispatch workflow <ArrowRight size={14}/></button></div>}
      {details==="payments"&&<div className="dn-panel-information"><DetailLine label="Payment">{selected.paymentMethod}</DetailLine><DetailLine label="Status"><Chip value={selected.paymentStatus}/></DetailLine><DetailLine label="Order total">{formatMoney(orderTotal(selected))}</DetailLine><p className="dn-helper">Payment entries here are fictional demo records. No funds move or provider is contacted.</p></div>}
      {details==="notes"&&<div className="dn-panel-information">{selected.notes.length?selected.notes.map((n,i)=><div className="dn-message" key={i}>{n}</div>):<Empty label="No notes on this order"/>}<button className="dn-btn primary" disabled={!canManage} onClick={()=>setModal("note")}>Add Internal Note</button><button className="dn-btn outline" onClick={()=>navigate("support")}>Open Support Conversations</button></div>}
     </>:<Empty label="Select an order"/>}
    </Card>
    {selected&&<div className="dn-order-footer"><Card title="Order Notes & Support" desc="Customer instructions and internal notes"><div className="dn-small-notes">{selected.notes.slice(-2).map((n,i)=><p key={i}>{n}</p>)}{!selected.notes.length&&<p>No notes yet.</p>}</div><button className="dn-text-btn" disabled={!canManage} onClick={()=>setModal("note")}>+ Add internal note</button></Card><Card title="Quick Actions"><div className="dn-quick-grid"><button className="dn-btn primary" onClick={focusDispatch}><Bike size={15}/> Dispatch / Assign Rider</button><button className="dn-btn outline" onClick={()=>navigate("support")}><MessageSquare size={15}/> Contact Customer</button><button className="dn-btn outline" disabled={!canManage||!isActive(selected)} onClick={()=>{setNewStatus(selected.status);setModal("status");}}><Edit3 size={15}/> Update Status</button><button className="dn-btn red" disabled={!canManage||!isActive(selected)} onClick={()=>{setCancelReason("");setModal("cancel");}}><XCircle size={15}/> Cancel Order</button></div></Card></div>}
   </div>
  </div>
  {selected&&modal==="cancel"&&<Modal title={"Cancel order #"+selected.id+"?"} subtitle="This updates all connected demo screens." onClose={()=>setModal(null)} onConfirm={doAction} confirmText="Confirm cancellation" disabled={cancelReason.trim().length<3} danger><label className="dn-field">Reason for cancellation<textarea value={cancelReason} onChange={e=>setCancelReason(e.target.value)} placeholder="Reason for this action" aria-label="Cancellation reason"/></label><p>No real order or payment will be affected.</p></Modal>}
  {selected&&modal==="note"&&<Modal title="Add internal note" subtitle={"Order #"+selected.id} onClose={()=>setModal(null)} onConfirm={doAction} confirmText="Save note" disabled={note.trim().length<2}><label className="dn-field">Internal note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Note visible to demo administrators" aria-label="Internal note"/></label></Modal>}
  {selected&&modal==="status"&&<Modal title="Update order status" subtitle={"Order #"+selected.id+" · "+selected.merchant} onClose={()=>setModal(null)} onConfirm={doAction} confirmText="Save status" disabled={!canManage||!isActive(selected)}><label className="dn-field">New status<select value={newStatus} onChange={e=>setNewStatus(e.target.value as OrderStatus)} aria-label="New order status">{allowedStatuses.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></label><p>Status transitions are simulated and recorded in the demo timeline. Rider-required milestones need an assigned rider.</p></Modal>}
 </div>;
}
