import React,{useEffect,useRef,useState} from "react";
import {AlertTriangle, ArrowRight, CheckCircle2, ChevronDown, Clock3, Headphones, ImagePlus, Mail, MessageCircle, MessageSquare, MoreHorizontal, Paperclip, Phone, Plus, Send, ShieldAlert, Smile, UserRound, Users, X} from "lucide-react";
import {displayTime,formatMoney,orderTotal} from "../data";
import type {Severity,SupportCase,SupportStatus} from "../phase2Data";
import {useDemo,canAct} from "../store";
import {Card,Chip,DetailLine,Empty,IconStat,Initials,Modal,SearchBox,SelectBox,Tabs} from "../ui";
const statusChoices:SupportStatus[]=["OPEN","IN_PROGRESS","WAITING_ON_USER","RESOLVED","CLOSED"];
const assignees=["Unassigned","John A.","Mary W.","Grace N.","Collins M.","Support Lead"];
export function SupportScreen({navigate,globalSearch,toast}:{navigate:(x:string)=>void;globalSearch:string;toast:(s:string)=>void}){
 const {data,act,role}=useDemo(),cases=data.phase2.support,canReply=canAct(role,"support"),canResolve=canAct(role,"resolve");
 const [tab,setTab]=useState("all"),[query,setQuery]=useState(""),[type,setType]=useState("all"),[priority,setPriority]=useState("all"),[selectedId,setSelectedId]=useState<string|null>(null),[panel,setPanel]=useState("conversation"),[composer,setComposer]=useState(""),[internal,setInternal]=useState(false),[modal,setModal]=useState<"create"|"status"|"simulate"|null>(null);
 const [newName,setNewName]=useState(""),[subject,setSubject]=useState(""),[newType,setNewType]=useState<SupportCase["participantType"]>("Customer"),[newPriority,setNewPriority]=useState<Severity>("MEDIUM"),[newOrder,setNewOrder]=useState(""),[resolution,setResolution]=useState(""),[targetStatus,setTargetStatus]=useState<SupportStatus>("IN_PROGRESS"),[mockResponse,setMockResponse]=useState("");
 const bottomRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{if(globalSearch)setQuery(globalSearch);},[globalSearch]);
 useEffect(()=>{const id=sessionStorage.getItem("deetoo.demo.focusSupport");if(id){setSelectedId(id);setTab("all");setQuery(id);sessionStorage.removeItem("deetoo.demo.focusSupport");}},[]);
 const counts={open:cases.filter(x=>x.status==="OPEN").length,progress:cases.filter(x=>x.status==="IN_PROGRESS").length,waiting:cases.filter(x=>x.status==="WAITING_ON_USER").length,resolved:cases.filter(x=>x.status==="RESOLVED").length};
 const filtered=cases.filter(x=>(tab==="all"||x.status===tab)&&(type==="all"||x.participantType===type)&&(priority==="all"||x.priority===priority)&&(x.id+" "+x.subject+" "+x.participantName).toLowerCase().includes(query.toLowerCase()));
 const selected=cases.find(x=>x.id===selectedId)||filtered[0];
 const order=selected?.orderId?data.orders.find(x=>x.id===selected.orderId):undefined;
 const party=selected?.participantType==="Merchant"?data.phase2.merchants.find(x=>x.name===selected.participantName):selected?.participantType==="Customer"?data.phase2.customers.find(x=>x.name===selected.participantName):data.riders.find(x=>x.name===selected?.participantName);
 const send=()=>{if(!selected||!canReply||composer.trim().length<2)return;act({type:"PHASE2_SUPPORT_REPLY",id:selected.id,message:composer,internal,actor:"ADMIN",by:"Demo Support Agent"});setComposer("");toast(internal?"Private internal note saved.":"Response added to the conversation.");setTimeout(()=>bottomRef.current?.scrollIntoView({behavior:"smooth",block:"nearest"}),0);};
 const simulate=()=>{if(!selected||mockResponse.trim().length<2)return;act({type:"PHASE2_SUPPORT_REPLY",id:selected.id,message:mockResponse,internal:false,by:selected.participantName,actor:selected.participantType.toUpperCase() as "CUSTOMER"|"MERCHANT"|"RIDER"});setModal(null);setMockResponse("");toast("Sample participant response appended.");};
 const create=()=>{if(!canReply||newName.trim().length<2||subject.trim().length<4)return;act({type:"PHASE2_SUPPORT_CREATE",name:newName,subject,participantType:newType,orderId:newOrder||null,priority:newPriority});setTab("all");setQuery("");setModal(null);toast("Support case created in the local demo.");setNewName("");setSubject("");setNewOrder("");};
 const saveStatus=()=>{if(!selected||!canResolve)return;if(["RESOLVED","CLOSED"].includes(targetStatus)&&resolution.trim().length<5)return;act({type:"PHASE2_SUPPORT_STATUS",id:selected.id,status:targetStatus,resolution});setModal(null);setResolution("");toast("Case status updated by a demo administrator.");};
 const linkedOrder=()=>{if(order){sessionStorage.setItem("deetoo.demo.focusOrder",order.id);navigate("orders");}else toast("No order is linked to this conversation.");};
 const participant=()=>{if(!selected)return;navigate(selected.participantType==="Customer"?"customers":selected.participantType==="Merchant"?"merchants":"riders");};
 return <div className="dn-screen" data-testid="screen-support">
  <div className="dn-title-row"><div><h1>Support & Conversations</h1><p>Manage customer, merchant and rider support cases from start to resolution.</p></div><div className="dn-inline-kpis"><IconStat label="Open Cases" value={counts.open} tone="red" icon={<AlertTriangle/>}/><IconStat label="In Progress" value={counts.progress} tone="blue" icon={<Clock3/>}/><IconStat label="Waiting on User" value={counts.waiting} tone="amber" icon={<UserRound/>}/><IconStat label="Resolved" value={counts.resolved} icon={<CheckCircle2/>}/></div><button className="dn-btn primary" onClick={()=>setModal("create")} disabled={!canReply}><Plus size={15}/> New Case</button></div>
  <div className="dn-support-grid">
   <Card className="dn-support-inbox">
    <Tabs ariaLabel="Support case filters" value={tab} onChange={setTab} tabs={[{key:"all",label:"All ("+cases.length+")"},...statusChoices.map(s=>({key:s,label:s.replaceAll("_"," ")+" ("+cases.filter(x=>x.status===s).length+")"}))]}/>
    <div className="dn-toolbar"><SearchBox placeholder="Search conversations..." value={query} onChange={setQuery}/><SelectBox label="Support type" value={type} onChange={setType} options={[{value:"all",label:"All Types"},...["Customer","Merchant","Rider"].map(x=>({value:x,label:x}))]}/><SelectBox label="Priority filter" value={priority} onChange={setPriority} options={[{value:"all",label:"All Priorities"},...["LOW","MEDIUM","HIGH","CRITICAL"].map(x=>({value:x,label:x}))]}/></div>
    <div className="dn-support-list">{filtered.length?filtered.map(c=><button className={"dn-support-item "+(selected?.id===c.id?"active":"")} key={c.id} onClick={()=>{setSelectedId(c.id);setPanel("conversation");setInternal(false);}}><Initials name={c.participantName}/><div className="dn-support-item-body"><div><b>{c.participantName}</b><Chip value={c.participantType}/><small>{displayTime(c.updatedAt)}</small></div><strong>{c.subject}</strong><p>{c.messages.filter(x=>!x.internal).at(-1)?.text.slice(0,61)||"New support request…"}</p></div><div className="dn-support-item-status"><Chip value={c.priority}/><Chip value={c.status}/></div></button>):<Empty label="No conversations match your filters"/>}</div>
    <div className="dn-list-footer">Showing {filtered.length} of {cases.length} conversations</div>
   </Card>
   <Card className="dn-conversation-card">
    {selected?<><div className="dn-conversation-heading"><div><div><h2>#{selected.id}</h2><Chip value={selected.priority}/><Chip value={selected.status}/></div><h3>{selected.subject}</h3><p>{selected.participantType} · {selected.participantName} · {selected.orderId?"Order #"+selected.orderId:"No linked order"}</p></div><button className="dn-btn outline" onClick={()=>{act({type:"PHASE2_SUPPORT_ASSIGN",id:selected.id,assignee:"Demo Support Agent"});toast("Support case assigned to you.");}} disabled={!canReply}>Assign to me</button></div>
     <Tabs ariaLabel="Conversation details" value={panel} onChange={setPanel} tabs={[{key:"conversation",label:"Conversation"},{key:"order",label:"Order Details"},{key:"notes",label:"Internal Notes ("+selected.messages.filter(m=>m.internal).length+")"},{key:"related",label:"Related Cases"}]}/>
     {panel==="conversation"&&<><div className="dn-chat-history" aria-label="Case conversation">
      {selected.messages.filter(m=>!m.internal).map(m=><div key={m.id} className={"dn-chat-msg "+(m.actor==="ADMIN"?"own":m.actor==="SYSTEM"?"system":"party")}><Initials name={m.by}/><div><div className="dn-chat-meta"><b>{m.by} {m.actor==="ADMIN"?"(Support Agent)":""}</b><span>{displayTime(m.at)}</span></div><p>{m.text}</p></div></div>)}
      <div ref={bottomRef}/>
     </div></>}
     {panel==="notes"&&<div className="dn-panel-information">{selected.messages.filter(m=>m.internal).length?selected.messages.filter(m=>m.internal).map(m=><div className="dn-note-block" key={m.id}><b>{m.by}</b><small>{displayTime(m.at)}</small><p>{m.text}</p></div>):<Empty label="No internal notes yet"/>}</div>}
     {panel==="order"&&<div className="dn-panel-information">{order?<><DetailLine label="Order">#{order.id}</DetailLine><DetailLine label="Merchant">{order.merchant}</DetailLine><DetailLine label="Customer">{order.customer}</DetailLine><DetailLine label="Status"><Chip value={order.status}/></DetailLine><DetailLine label="Total">{formatMoney(orderTotal(order))}</DetailLine><button className="dn-btn outline" onClick={linkedOrder}>View Order <ArrowRight size={13}/></button></>:<Empty label="No order attached to this conversation"/>}</div>}
     {panel==="related"&&<div className="dn-panel-information">{cases.filter(c=>c.participantName===selected.participantName&&c.id!==selected.id).slice(0,8).map(c=><button className="dn-support-related" key={c.id} onClick={()=>{setSelectedId(c.id);setPanel("conversation");}}><b>#{c.id}</b><span>{c.subject}</span><Chip value={c.status}/></button>)}{!cases.some(c=>c.participantName===selected.participantName&&c.id!==selected.id)&&<Empty label="No related cases for this person"/>}</div>}
     <div className="dn-support-compose"><Tabs ariaLabel="Reply or internal note" value={internal?"internal":"reply"} onChange={x=>setInternal(x==="internal")} tabs={[{key:"reply",label:"Reply"},{key:"internal",label:"Internal Note"}]}/><textarea value={composer} onChange={e=>setComposer(e.target.value)} aria-label={internal?"Private internal note":"Reply message"} placeholder={internal?"Add a private note visible only to staff…":"Type your message to the participant…"}/><div><div><button className="dn-iconbutton" aria-label="Simulate participant response" title="Simulate participant response" onClick={()=>setModal("simulate")}><MessageSquare size={16}/></button><span>{internal?"Private staff-only note":"Visible to the involved party in this demo"}</span></div><button className="dn-btn primary" onClick={send} disabled={!canReply||composer.trim().length<2}><Send size={14}/> {internal?"Save Note":"Send"}</button></div></div>
    </>:<Empty label="Choose a conversation from the inbox"/>}
   </Card>
   <div className="dn-support-context">
    {selected?<><Card title={selected.participantType+" Details"} action={<button className="dn-text-btn" onClick={participant}>View Profile →</button>}><div className="dn-support-contact"><Initials name={selected.participantName}/><div><strong>{selected.participantName}</strong><p>{selected.participantType} · {party&&"email" in party?party.email:"Demo profile"}</p></div></div><DetailLine label="Type">{selected.participantType}</DetailLine><DetailLine label="Assigned to">{selected.assignedTo}</DetailLine></Card>
    <Card title="Order Information" action={<button className="dn-text-btn" onClick={linkedOrder}>View Order →</button>}>{order?<><div className="dn-support-ordercard"><b>#{order.id}</b><Chip value={order.status}/></div><p>{order.merchant} — {order.area}</p><DetailLine label="Total">{formatMoney(orderTotal(order))}</DetailLine></>:<Empty label="No linked order"/>}</Card>
    <Card title="Case Metadata"><DetailLine label="Case ID">#{selected.id}</DetailLine><DetailLine label="Priority"><Chip value={selected.priority}/></DetailLine><DetailLine label="Status"><Chip value={selected.status}/></DetailLine><DetailLine label="Assigned to">{selected.assignedTo}</DetailLine><DetailLine label="Created">{displayTime(selected.createdAt)}</DetailLine><DetailLine label="Last activity">{displayTime(selected.updatedAt)}</DetailLine><DetailLine label="Satisfaction"><Chip value={selected.satisfaction}/></DetailLine></Card>
    <Card title="Actions"><div className="dn-support-actions"><button className="dn-btn outline" disabled={!canReply} onClick={()=>{setInternal(true);setPanel("notes");}}>Add Internal Note</button><button className="dn-btn red" disabled={!canResolve} onClick={()=>{setTargetStatus("IN_PROGRESS");setResolution("");setModal("status");}}>Escalate / Resolve</button><SelectBox label="Assign support agent" value={selected.assignedTo} onChange={v=>{if(canReply)act({type:"PHASE2_SUPPORT_ASSIGN",id:selected.id,assignee:v});}} options={assignees.concat(selected.assignedTo&&!assignees.includes(selected.assignedTo)?[selected.assignedTo]:[]).map(x=>({value:x,label:x}))}/><button className="dn-btn outline" onClick={()=>setModal("simulate")}>Simulate Participant Reply</button></div>{selected.status==="RESOLVED"&&selected.satisfaction==="PENDING"&&<div className="dn-satisfaction"><p>Simulate whether the participant is satisfied:</p><button disabled={!canReply} onClick={()=>act({type:"PHASE2_SUPPORT_SATISFACTION",id:selected.id,outcome:"SATISFIED"})}>Satisfied</button><button disabled={!canReply} onClick={()=>act({type:"PHASE2_SUPPORT_SATISFACTION",id:selected.id,outcome:"NOT_SATISFIED"})}>Still needs help</button></div>}</Card></>:<Empty label="Select a support case"/>}
   </div>
  </div>
  {modal==="create"&&<Modal title="Open support conversation" subtitle="Create a new frontend-only conversation" onClose={()=>setModal(null)} onConfirm={create} disabled={!canReply||newName.trim().length<2||subject.trim().length<4} confirmText="Open case"><label className="dn-field">Participant name<input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Customer, merchant or rider name"/></label><label className="dn-field">Participant type<select value={newType} onChange={e=>setNewType(e.target.value as SupportCase["participantType"])}>{["Customer","Merchant","Rider"].map(x=><option key={x}>{x}</option>)}</select></label><label className="dn-field">Subject<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="What is the issue?"/></label><label className="dn-field">Priority<select value={newPriority} onChange={e=>setNewPriority(e.target.value as Severity)}>{["LOW","MEDIUM","HIGH","CRITICAL"].map(x=><option key={x}>{x}</option>)}</select></label><label className="dn-field">Order (optional)<select value={newOrder} onChange={e=>setNewOrder(e.target.value)}><option value="">No order linked</option>{data.orders.slice(0,55).map(o=><option key={o.id} value={o.id}>{o.id}</option>)}</select></label></Modal>}
  {modal==="status"&&selected&&<Modal title="Admin case resolution" subtitle={selected.id+" · Status is controlled by an authorized demo administrator"} onClose={()=>setModal(null)} onConfirm={saveStatus} disabled={!canResolve||["RESOLVED","CLOSED"].includes(targetStatus)&&resolution.trim().length<5} confirmText="Save case status"><label className="dn-field">New status<select value={targetStatus} onChange={e=>setTargetStatus(e.target.value as SupportStatus)}>{statusChoices.filter(s=>!(s==="CLOSED"&&!(selected.status==="RESOLVED"&&selected.satisfaction==="SATISFIED"))).map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label className="dn-field">Resolution / audit note<textarea value={resolution} onChange={e=>setResolution(e.target.value)} placeholder="Explain the resolution or escalation"/></label><p>Resolved cases await simulated participant satisfaction. Dissatisfaction reopens the case; only admins can close the final case.</p></Modal>}
  {modal==="simulate"&&selected&&<Modal title="Simulate participant response" subtitle="Preview-only; no real message is sent" onClose={()=>setModal(null)} onConfirm={simulate} disabled={mockResponse.trim().length<2} confirmText="Add demo response"><label className="dn-field">Participant message<textarea value={mockResponse} onChange={e=>setMockResponse(e.target.value)} placeholder={"Response from "+selected.participantName}/></label></Modal>}
 </div>;
}
