import '../../../src/global-polyfill';
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { MerchantApp } from '../../merchant/src/MerchantApp';
import { MerchantPrototype } from './prototype/MerchantPrototype';
import '../../../src/index.css';
import { installTheme } from '../../../packages/ui/src/theme';
installTheme(document.documentElement);
const preview = window.location.pathname === '/prototype' || window.location.pathname.startsWith('/prototype/');
createRoot(document.getElementById('root')!).render(<StrictMode>{preview ? <MerchantPrototype /> : <MerchantApp />}</StrictMode>);
