import React, { useState } from "react";
import { CalendarClock, Check, ChefHat, Clock3, ImagePlus, LocateFixed, MapPin, Settings2, Store, Truck, Utensils, Plus, Save, Navigation } from "lucide-react";

type BranchData = { name: string; display: string; description: string; street: string; city: string; phone: string; email: string; latitude: string; longitude: string; prep: string; minOrder: string; image: string };
type Hours = { day: string; active: boolean; open: string; close: string };
const defaultBranch: BranchData = {name:"Juja Branch",display:"Juja Branch",description:"Serving fresh and delicious meals, drinks and snacks. Quality food, fast preparation and great service.",street:"Kalimoni",city:"Juja",phone:"+254 700 123 456",email:"juja@deetoo.test",latitude:"-1.102619",longitude:"37.010704",prep:"20",minOrder:"0",image:""};
const initialHours:Hours[] = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].map(day=>({day,active:true,open:"08:00",close:day==="Friday"||day==="Saturday"?"23:59":"23:00"}));
function readJson<T>(key:string,fallback:T):T{try{const value=localStorage.getItem(key);return value?JSON.parse(value) as T:fallback;}catch{return fallback;}}
export function DemoBadge({children,kind="green"}:{children:React.ReactNode;kind?:string}){return <span className={"mp-pill mp-"+kind}>{children}</span>;}
export function DemoCard({children,className=""}:{children:React.ReactNode;className?:string}){return <section className={"mp-white-card "+className}>{children}</section>;}
export function BranchBanner({store,onAction,action="View on map"}:{store:string;onAction:()=>void;action?:string}){return <div className="mp-branch-banner"><div className="mp-restaurant-photo" aria-hidden="true">🏮</div><span><b>Juja Branch</b><small>Kalimoni, Juja</small></span><DemoBadge>{store}</DemoBadge><button className="mp-outline" onClick={onAction}><MapPin size={15}/>{action}</button></div>;}
export function DemoHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}){return <div className="mp-head"><div><span className="mp-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>;}
export function PrototypeBranch({store,setStore,notify}:{store:"Open"|"Paused"|"Closed";setStore:(v:"Open"|"Paused"|"Closed")=>void;notify:(s:string)=>void}){
 const [branch,setBranch]=useState<BranchData>(()=>readJson("mp-demo-branch",defaultBranch));
 const [hours,setHours]=useState<Hours[]>(()=>readJson("mp-demo-hours",initialHours));
 const [tab,setTab]=useState("General");
 const [dialog,setDialog]=useState<"location"|"advanced"|"rules"|"upload"|"image-preview"|null>(null);
 const [pickup,setPickup]=useState(true),[delivery,setDelivery]=useState(true),[tableService,setTableService]=useState(false);
 const [minBasket,setMinBasket]=useState("0"),[maxConcurrent,setMaxConcurrent]=useState("30");
 const update=(key:keyof BranchData,value:string)=>setBranch(prev=>({...prev,[key]:value}));
 const save=()=>{if(!branch.name.trim()||!branch.street.trim()||!branch.city.trim()||!Number.isFinite(Number(branch.latitude))||Math.abs(Number(branch.latitude))>90||!Number.isFinite(Number(branch.longitude))||Math.abs(Number(branch.longitude))>180){notify("Check required branch details and coordinates.");return;}localStorage.setItem("mp-demo-branch",JSON.stringify(branch));localStorage.setItem("mp-demo-hours",JSON.stringify(hours));notify("Branch settings saved in frontend prototype");};
 const navigate=(section:string)=>{setTab(section);if(section==="Ordering rules")setDialog("rules");else if(section==="Advanced")setDialog("advanced");else document.getElementById("mp-branch-"+section.toLowerCase().replace(/\s+/g,"-"))?.scrollIntoView({behavior:"smooth",block:"center"});};
 const updateHour=(day:string,patch:Partial<Hours>)=>setHours(prev=>prev.map(row=>row.day===day?{...row,...patch}:row));
 const onImage=(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;if(!file.type.startsWith("image/")||file.size>5*1024*1024){notify("Choose a JPG, PNG or WebP image under 5 MB");return;}const reader=new FileReader();reader.onload=()=>{update("image",String(reader.result));setDialog(null);notify("Branch image updated locally. Save branch settings to keep changes.");};reader.readAsDataURL(file);};
 return <div className="mp-p2">
   <DemoHeading eyebrow="BRANCH SETTINGS" title="Branch settings" description="Manage your branch information, location, operating hours and preparation settings." action={<BranchBanner store={store} onAction={()=>setDialog("location")}/>} />
   <nav className="mp-p2-section-tabs" aria-label="Branch settings sections">{[["General",Store],["Location",MapPin],["Operating hours",Clock3],["Preparation",ChefHat],["Delivery & service",Truck],["Ordering rules",Settings2],["Advanced",Settings2]].map(([name,Icon]:any)=><button key={name} aria-current={tab===name?"page":undefined} className={tab===name?"active":""} onClick={()=>navigate(name)}><Icon size={19}/>{name}</button>)}</nav>
   <div className="mp-p2-branch-grid">
     <DemoCard className="mp-p2-branch-general" ><div id="mp-branch-general"/><h2><Store/>General information</h2><p>Basic details about this branch. This information is shown to customers.</p>
       <label>Branch name <b>*</b><input value={branch.name} onChange={e=>update("name",e.target.value)} required/></label>
       <label>Display name <b>*</b><input value={branch.display} onChange={e=>update("display",e.target.value)} required/></label>
       <label>Business description<textarea rows={3} value={branch.description} onChange={e=>update("description",e.target.value)}/></label>
       <label>Phone number<input type="tel" value={branch.phone} onChange={e=>update("phone",e.target.value)}/></label>
       <label>Email<input type="email" value={branch.email} onChange={e=>update("email",e.target.value)}/></label>
       <span className="mp-p2-label">Status</span><div className="mp-p2-status-options">{(["Open","Paused","Closed"] as const).map(name=><button className={store===name?"active":""} key={name} aria-pressed={store===name} onClick={()=>setStore(name)}><Check size={17}/><span><b>{name}</b><small>{name==="Open"?"Accepting orders":name==="Paused"?"Temporarily paused":"Not accepting orders"}</small></span></button>)}</div>
     </DemoCard>
     <DemoCard className="mp-p2-branch-location"><div id="mp-branch-location"/><h2><MapPin/>Location</h2><p>Set your branch address and location on the map.</p>
       <label>Street address <b>*</b><input value={branch.street} onChange={e=>update("street",e.target.value)}/></label>
       <label>City / Town <b>*</b><input value={branch.city} onChange={e=>update("city",e.target.value)}/></label>
       <div className="mp-p2-row"><label>Latitude <b>*</b><input type="number" step="any" value={branch.latitude} onChange={e=>update("latitude",e.target.value)}/></label><label>Longitude <b>*</b><input type="number" step="any" value={branch.longitude} onChange={e=>update("longitude",e.target.value)}/></label></div>
       <button type="button" className="mp-p2-location-map" onClick={()=>setDialog("location")} aria-label="Open location map preview"><span className="mp-p2-map-roads"/><span className="mp-p2-map-pin"><MapPin size={33} fill="currentColor"/></span><span className="mp-p2-map-label"><b>{branch.display}</b><small>{branch.street}, {branch.city}</small></span><span className="mp-p2-map-caption">Map preview — illustrative, not live mapping</span></button>
       <div className="mp-p2-bottom-actions"><button className="mp-outline" onClick={()=>{if(!navigator.geolocation){notify("Geolocation is unavailable.");return;}navigator.geolocation.getCurrentPosition(pos=>{setBranch(x=>({...x,latitude:String(pos.coords.latitude),longitude:String(pos.coords.longitude)}));notify("Current location applied locally");},()=>notify("Location permission denied or GPS unavailable"));}}><LocateFixed size={16}/>Use current location</button><button className="mp-primary" onClick={()=>setDialog("location")}>Update location</button></div>
     </DemoCard>
     <DemoCard className="mp-p2-branch-hours"><div id="mp-branch-operating-hours"/><h2><Clock3/>Operating hours</h2><p>Set when this branch accepts orders.</p><div className="mp-p2-hours-list">{hours.map(row=><div className="mp-p2-hours-row" key={row.day}><span>{row.day}</span><button role="switch" aria-checked={row.active} aria-label={row.day+" open"} className={"mp-switch "+(row.active?"on":"")} onClick={()=>updateHour(row.day,{active:!row.active})}><span/></button>{row.active?<div className="mp-p2-hour-inputs"><input type="time" aria-label={row.day+" opening time"} value={row.open} onChange={e=>updateHour(row.day,{open:e.target.value})}/><span>–</span><input type="time" aria-label={row.day+" closing time"} value={row.close} onChange={e=>updateHour(row.day,{close:e.target.value})}/></div>:<em>Closed all day</em>}</div>)}</div></DemoCard>
     <DemoCard className="mp-p2-branch-prep"><div id="mp-branch-preparation"/><h2><ChefHat/>Preparation settings</h2><p>Configure preparation time and minimum order requirements.</p><div className="mp-p2-row"><label>Default preparation time (minutes) <b>*</b><input type="number" min="1" value={branch.prep} onChange={e=>update("prep",e.target.value)}/></label><label>Minimum order amount (Ksh) <b>*</b><input type="number" min="0" value={branch.minOrder} onChange={e=>update("minOrder",e.target.value)}/></label></div></DemoCard>
     <DemoCard className="mp-p2-branch-delivery"><div id="mp-branch-delivery-&-service"/><h2><Truck/>Delivery & service options</h2><p>Manage how this branch fulfills orders.</p><div className="mp-p2-service-checks"><label><input type="checkbox" checked={pickup} onChange={e=>setPickup(e.target.checked)}/><span><strong>Dine-in / Pickup</strong><small>Allow customers to pick up orders</small></span></label><label><input type="checkbox" checked={delivery} onChange={e=>setDelivery(e.target.checked)}/><span><strong>Delivery</strong><small>Allow delivery orders from nearby areas</small></span></label><label><input type="checkbox" checked={tableService} onChange={e=>setTableService(e.target.checked)}/><span><strong>Table service (QR orders)</strong><small>For in-restaurant QR code ordering</small></span></label></div></DemoCard>
     <DemoCard className="mp-p2-branch-image"><h2><ImagePlus/>Branch image</h2><p>Upload a photo for this branch. This will be shown to customers.</p><div className="mp-p2-image-box">{branch.image?<img src={branch.image} alt="Branch preview"/>:<div className="mp-p2-image-placeholder">🏮</div>}<label className="mp-p2-upload"><ImagePlus size={21}/>Upload new image <small>JPG, PNG or WebP · Max 5MB</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={onImage}/></label></div></DemoCard>
   </div><div className="mp-p2-save-bar"><span>Changes to branch settings are stored only in this frontend preview.</span><button className="mp-primary" onClick={save}><Save size={16}/>Save branch settings</button></div>
   {dialog&&<div className="mp-modal-overlay" onMouseDown={e=>e.target===e.currentTarget&&setDialog(null)}><section className="mp-modal" role="dialog" aria-modal="true" aria-label={dialog}><div className="mp-modal-head"><h2>{dialog==="location"?"Branch location":dialog==="rules"?"Ordering rules":dialog==="advanced"?"Advanced settings":"Branch image"}</h2><button aria-label="Close" onClick={()=>setDialog(null)}>✕</button></div>{dialog==="location"?<><p>Set the pickup point for {branch.display}. Coordinates are editable in the Location panel. This illustration is not a live street map.</p><div className="mp-p2-location-map mp-p2-location-large"><span className="mp-p2-map-roads"/><span className="mp-p2-map-pin"><MapPin size={40}/></span><span className="mp-p2-map-label">{branch.latitude}, {branch.longitude}</span></div><button className="mp-primary mp-full" onClick={()=>{setDialog(null);save();}}>Confirm location</button></>:dialog==="rules"?<><p>Configure order rules for this branch (frontend prototype only).</p><label>Minimum basket amount (Ksh)<input type="number" value={minBasket} min="0" onChange={e=>setMinBasket(e.target.value)}/></label><label>Maximum concurrent orders<input type="number" min="1" value={maxConcurrent} onChange={e=>setMaxConcurrent(e.target.value)}/></label><button className="mp-primary mp-full" onClick={()=>{setDialog(null);notify("Ordering rules updated locally")}}>Save ordering rules</button></>:dialog==="advanced"?<><p>Advanced controls are retained for the backend mapping stage. No live account or branch configuration will be changed.</p><button className="mp-outline" onClick={()=>{localStorage.removeItem("mp-demo-branch");localStorage.removeItem("mp-demo-hours");setBranch(defaultBranch);setHours(initialHours);setDialog(null);notify("Demo branch preferences reset");}}>Reset demo settings</button></>:null}</section></div>}
 </div>;
}
