import React, { useState } from "react";
import { AlertTriangle, Bell, Check, ChevronRight, Clock3, KeyRound, Laptop, LockKeyhole, LogOut, Monitor, ShieldCheck, Smartphone, TabletSmartphone, Trash2, UserRound, X } from "lucide-react";
import { BranchBanner, DemoBadge, DemoCard, DemoHeading } from "./PrototypeBranch";

type Session={id:number;device:string;location:string;time:string;current:boolean;trusted:boolean;browser:string};
type Login={id:number;date:string;device:string;location:string;status:"Success"|"Failed"};
const sessionSeed:Session[]=[
{id:1,device:"Linux · Chrome 118.0.0",location:"Kalimoni, Juja, Kenya",time:"Just now",current:true,trusted:true,browser:"desktop"},
{id:2,device:"Android · Chrome 118.0.0",location:"Juja, Kenya",time:"Oct 9, 2026 10:18 AM",current:false,trusted:true,browser:"phone"},
{id:3,device:"Windows · Edge 117.0.0",location:"Nairobi, Kenya",time:"Oct 8, 2026 4:32 PM",current:false,trusted:true,browser:"desktop"}];
const loginSeed:Login[]=[
{id:1,date:"Oct 9, 2026 12:24 PM",device:"Linux · Chrome",location:"Kalimoni, Juja",status:"Success"},
{id:2,date:"Oct 9, 2026 10:18 AM",device:"Android · Chrome",location:"Juja, Kenya",status:"Success"},
{id:3,date:"Oct 8, 2026 4:32 PM",device:"Windows · Edge",location:"Nairobi, Kenya",status:"Success"},
{id:4,date:"Oct 7, 2026 9:15 PM",device:"Android · Chrome",location:"Nairobi, Kenya",status:"Success"},
{id:5,date:"Oct 6, 2026 2:11 PM",device:"Linux · Firefox",location:"Kalimoni, Juja",status:"Success"},
{id:6,date:"Oct 5, 2026 11:03 AM",device:"Windows · Chrome",location:"Nakuru, Kenya",status:"Failed"}];
function readLocal<T>(key:string,fallback:T):T{try{const val=localStorage.getItem(key);return val?JSON.parse(val) as T:fallback;}catch{return fallback;}}
export function PrototypeSecurity({store,onNavigate,notify}:{store:string;onNavigate:(s:string)=>void;notify:(s:string)=>void}){
 const [sessions,setSessions]=useState<Session[]>(()=>readLocal("mp-demo-sessions",sessionSeed));
 const [loginHistory]=useState<Login[]>(loginSeed);
 const [historyAll,setHistoryAll]=useState(false);
 const [twoFactor,setTwoFactor]=useState(()=>readLocal("mp-demo-2fa",true));
 const [deactivated,setDeactivated]=useState(()=>readLocal("mp-demo-deactivated",false));
 const [dialog,setDialog]=useState<"password"|"2fa"|"trusted"|"deactivate"|"session"|"history"|"all"|null>(null);
 const [chosen,setChosen]=useState<number|null>(null);
 const [password,setPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState("");
 const saveSessions=(next:Session[])=>{setSessions(next);localStorage.setItem("mp-demo-sessions",JSON.stringify(next));};
 const revoke=(id:number)=>{saveSessions(sessions.filter(x=>x.id!==id));setDialog(null);notify("Session revoked in frontend preview");};
 const logoutAll=()=>{saveSessions([]);setDialog(null);notify("All demo sessions signed out. No real tokens were revoked.");};
 const toggleTrust=(id:number)=>{saveSessions(sessions.map(x=>x.id===id?{...x,trusted:!x.trusted}:x));notify("Device trust changed in frontend preview");};
 const trustedCount=sessions.filter(s=>s.trusted&&!s.current).length;
 const deviceIcon=(v:string)=>v==="phone"?<Smartphone size={25}/>:<Monitor size={26}/>;
 return <div className="mp-p2">
  <DemoHeading eyebrow="ACCOUNT" title="Security & sessions" description="Keep your account secure and manage where it is being accessed." action={<BranchBanner store={store} action="Back to dashboard" onAction={()=>onNavigate("orders")}/>} />
  <div className="mp-p2-security-stats">
    <div className="mp-p2-security-stat"><span className="mp-p2-stat-icon mp-green"><ShieldCheck size={27}/></span><div><small>Active sessions</small><strong>{sessions.length}</strong><p>Devices currently signed in</p></div></div>
    <div className="mp-p2-security-stat"><span className="mp-p2-stat-icon mp-blue"><Monitor size={27}/></span><div><small>Trusted devices</small><strong>{trustedCount}</strong><p>Devices you've marked as trusted</p></div></div>
    <div className="mp-p2-security-stat"><span className="mp-p2-stat-icon mp-blue"><Clock3 size={27}/></span><div><small>Last login</small><strong>Today, 12:24 PM</strong><p>Kalimoni, Juja · Chrome on Linux</p></div></div>
    <div className="mp-p2-security-stat"><span className="mp-p2-stat-icon mp-orange"><LockKeyhole size={27}/></span><div><small>Security status</small><strong className="mp-p2-security-strong">Strong <span/></strong><p>Illustrative security score</p></div></div>
  </div>
  <div className="mp-p2-security-grid">
    <DemoCard><div className="mp-p2-card-head"><div><h2>Active sessions</h2><p>These are the devices currently signed in to your account.</p></div><button className="mp-p2-danger-soft" onClick={()=>setDialog("all")}><LogOut size={15}/> Sign out from all devices</button></div><div className="mp-p2-sessions">{sessions.map(session=><div className={"mp-p2-session "+(session.current?"current":"")} key={session.id}>{deviceIcon(session.browser)}<div><span>{session.current&&<DemoBadge>Current session</DemoBadge>}<strong>{session.device}</strong></span><p>⌖ {session.location} · {session.current?"This device":session.time}</p></div><div className="mp-p2-session-side"><small>{session.time}</small>{session.trusted&&<DemoBadge>{session.current?"Current":"Trusted"}</DemoBadge>}{!session.current&&<button aria-label={"Manage "+session.device} onClick={()=>{setChosen(session.id);setDialog("session");}}>⋮</button>}</div></div>)}{sessions.length===0&&<div className="mp-p2-empty">All preview sessions have been signed out. <button onClick={()=>{saveSessions(sessionSeed);notify("Demo sessions restored");}}>Restore demo sessions</button></div>}</div></DemoCard>
    <DemoCard><div className="mp-p2-card-head"><div><h2>Login history</h2><p>Recent sign-in activity on your account.</p></div><button className="mp-outline" onClick={()=>setHistoryAll(!historyAll)}>{historyAll?"Show less":"View all"}</button></div><div className="mp-table-scroll"><table><thead><tr><th>Date & time</th><th>Device</th><th>Location</th><th>Status</th><th>Actions</th></tr></thead><tbody>{(historyAll?loginHistory:loginHistory.slice(0,6)).map(row=><tr key={row.id}><td>{row.date}</td><td>{row.device}</td><td>{row.location}</td><td><DemoBadge kind={row.status==="Success"?"green":"red"}>{row.status}</DemoBadge></td><td><button aria-label={"Inspect login "+row.date} onClick={()=>{setChosen(row.id);setDialog("history");}}>⋮</button></td></tr>)}</tbody></table></div><small className="mp-p2-data-note">Illustrative login history, not authenticated security events.</small></DemoCard>
    <DemoCard><div className="mp-p2-card-head"><div><h2>Security settings</h2><p>Manage your account security preferences.</p></div></div><div className="mp-p2-security-options"><button onClick={()=>setDialog("password")}><LockKeyhole/><span><strong>Change password</strong><small>Update your password regularly to keep your account secure.</small></span><ChevronRight/></button><button onClick={()=>setDialog("2fa")}><ShieldCheck/><span><strong>Two-factor authentication (2FA)</strong><small>Add an extra layer of security to your account.</small></span><DemoBadge>{twoFactor?"Enabled":"Disabled"}</DemoBadge><ChevronRight/></button><button onClick={()=>setDialog("trusted")}><Laptop/><span><strong>Trusted devices</strong><small>Manage devices that you trust and won't require additional verification.</small></span><ChevronRight/></button></div></DemoCard>
    <DemoCard><div className="mp-p2-card-head"><div><h2 className="mp-p2-danger-title">Danger zone</h2><p>These actions can affect your account access and data.</p></div></div><div className="mp-p2-danger-list"><div><span><Trash2/></span><div><strong>Sign out from all devices</strong><small>This will end all active demo sessions, including your current one.</small></div><button className="mp-p2-danger-button" onClick={()=>setDialog("all")}>Sign out all</button></div><div><span><AlertTriangle/></span><div><strong>{deactivated?"Reactivate account":"Deactivate account"}</strong><small>Temporarily disable your merchant access. You can reactivate it later.</small></div><button className="mp-p2-danger-outline" onClick={()=>setDialog("deactivate")}>{deactivated?"Reactivate":"Deactivate"}</button></div></div></DemoCard>
  </div>
  {dialog&&<div className="mp-modal-overlay" onMouseDown={e=>e.target===e.currentTarget&&setDialog(null)}><section className="mp-modal" role="dialog" aria-modal="true" aria-label={dialog}><div className="mp-modal-head"><h2>{dialog==="password"?"Change password":dialog==="2fa"?"Two-factor authentication":dialog==="trusted"?"Trusted devices":dialog==="deactivate"?(deactivated?"Reactivate account":"Deactivate account"):dialog==="session"?"Manage session":dialog==="history"?"Login event":"Sign out all devices"}</h2><button aria-label="Close" onClick={()=>setDialog(null)}><X/></button></div>
    {dialog==="password"&&<form onSubmit={e=>{e.preventDefault();if(password!==confirmPassword){notify("Passwords must match");return;}setPassword("");setConfirmPassword("");setDialog(null);notify("Demo password form submitted. No credentials changed.");}}><p>Password changes are simulated in this isolated frontend preview. Never use a real password here.</p><label>New demo password<input type="password" autoComplete="new-password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirm demo password<input type="password" autoComplete="new-password" minLength={8} required value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label><button className="mp-primary mp-full">Save demo password</button></form>}
    {dialog==="2fa"&&<><p>Enable or disable the example two-factor authentication state. Real enrollment, QR codes and recovery codes require authentication services.</p><div className="mp-p2-toggle-row"><strong>Two-factor authentication</strong><button role="switch" className={"mp-switch "+(twoFactor?"on":"")} aria-checked={twoFactor} aria-label="Two-factor authentication" onClick={()=>{setTwoFactor(!twoFactor);localStorage.setItem("mp-demo-2fa",JSON.stringify(!twoFactor));}}><span/></button></div><button className="mp-primary mp-full" onClick={()=>{setDialog(null);notify("2FA preference updated locally (not real authentication)");}}>Done</button></>}
    {dialog==="trusted"&&<><p>Manage trust for the devices shown in the active sessions list.</p>{sessions.map(s=><div className="mp-p2-modal-device" key={s.id}><span>{deviceIcon(s.browser)} {s.device}</span><button className="mp-outline" onClick={()=>toggleTrust(s.id)}>{s.trusted?"Untrust":"Trust"}</button></div>)}<button className="mp-primary mp-full" onClick={()=>setDialog(null)}>Done</button></>}
    {dialog==="session"&&<><p>{sessions.find(s=>s.id===chosen)?.device||"Device"}</p><div className="mp-p2-modal-device"><button className="mp-outline" onClick={()=>{if(chosen!=null)toggleTrust(chosen);}}>{sessions.find(s=>s.id===chosen)?.trusted?"Untrust device":"Trust device"}</button><button className="mp-p2-danger-button" onClick={()=>{if(chosen!=null)revoke(chosen);}}>Revoke session</button></div></>}
    {dialog==="history"&&<><p>Event details (illustrative):</p>{Object.entries(loginHistory.find(x=>x.id===chosen)||{}).map(([key,value])=><div className="mp-modal-row" key={key}>{key}<strong>{String(value)}</strong></div>)}</>}
    {dialog==="all"&&<><p>Are you sure? All locally simulated sessions will be removed. This does not sign out any real user.</p><button className="mp-p2-danger-button mp-full" onClick={logoutAll}>Confirm sign out all</button></>}
    {dialog==="deactivate"&&<><p>{deactivated?"Restore this account's demo state?":"Deactivate this account in the prototype? This does not affect merchant access on the backend."}</p><button className="mp-p2-danger-button mp-full" onClick={()=>{setDeactivated(!deactivated);localStorage.setItem("mp-demo-deactivated",JSON.stringify(!deactivated));setDialog(null);notify("Account state changed in frontend preview only");}}>{deactivated?"Reactivate demo account":"Deactivate demo account"}</button></>}
  </section></div>}
 </div>;
}
