/** Stitch structured palette. CSS variables are installed by the existing SPA entry point. */
export const tokens = {
  colors: {
    brand: {
      primary: "#b02700",
      primaryHover: "#8a1c00",
      primaryLight: "#ffdad2",
      accent: "#006d42",
    },
    neutral: {
      canvas: "#fbf9f6",
      surface: "#ffffff",
      surfaceRaised: "#f5f3f0",
      border: "#e3beb6",
      textPrimary: "#1b1c1a",
      textSecondary: "#5a413a",
      textMuted: "#8f7069",
    },
    status: {
      success: "#006d42",
      warning: "#9a5700",
      error: "#ba1a1a",
      info: "#1a73e8",
    },
  },
  palette: {
    surface: "#fbf9f6",
    "surface-dim": "#dbdad7",
    "surface-bright": "#fbf9f6",
    "surface-container-lowest": "#ffffff",
    "surface-container-low": "#f5f3f0",
    "surface-container": "#efeeeb",
    "surface-container-high": "#eae8e5",
    "surface-container-highest": "#e4e2df",
    "on-surface": "#1b1c1a",
    "on-surface-variant": "#5a413a",
    "inverse-surface": "#30312f",
    "inverse-on-surface": "#f2f0ed",
    outline: "#8f7069",
    "outline-variant": "#e3beb6",
    "surface-tint": "#b42902",
    primary: "#b02700",
    "on-primary": "#ffffff",
    "primary-container": "#d3401a",
    "on-primary-container": "#fffbff",
    "inverse-primary": "#ffb4a2",
    secondary: "#006d42",
    "on-secondary": "#ffffff",
    "secondary-container": "#8ff8ba",
    "on-secondary-container": "#007346",
    tertiary: "#5c5b5e",
    "on-tertiary": "#ffffff",
    "tertiary-container": "#757476",
    "on-tertiary-container": "#fffbfe",
    error: "#ba1a1a",
    "on-error": "#ffffff",
    "error-container": "#ffdad6",
    "on-error-container": "#93000a",
    "primary-fixed": "#ffdad2",
    "primary-fixed-dim": "#ffb4a2",
    "on-primary-fixed": "#3c0700",
    "on-primary-fixed-variant": "#8a1c00",
    "secondary-fixed": "#8ff8ba",
    "secondary-fixed-dim": "#72dba0",
    "on-secondary-fixed": "#002111",
    "on-secondary-fixed-variant": "#005231",
    "tertiary-fixed": "#e5e1e4",
    "tertiary-fixed-dim": "#c8c6c8",
    "on-tertiary-fixed": "#1b1b1d",
    "on-tertiary-fixed-variant": "#474649",
    background: "#fbf9f6",
    "on-background": "#1b1c1a",
    "surface-variant": "#e4e2df",
  },
  typography: {
    heading: "Epilogue, ui-sans-serif, system-ui, sans-serif",
    body: "Manrope, ui-sans-serif, system-ui, sans-serif",
    sizes: {
      display: "3rem",
      displayMobile: "2.125rem",
      headline: "2rem",
      title: "1.5rem",
      subtitle: "1.25rem",
      body: ".9375rem",
      small: ".8125rem",
      label: ".6875rem",
    },
    weights: { regular: 400, medium: 600, bold: 700, display: 800 },
    lineHeights: {
      display: "3.5rem",
      displayMobile: "2.5rem",
      headline: "2.375rem",
      title: "1.875rem",
      body: "1.375rem",
      small: "1.125rem",
    },
  },
  radius: {
    sm: ".25rem",
    md: ".5rem",
    lg: "1rem",
    xl: "1.5rem",
    full: "9999px",
  },
  spacing: {
    xs: ".25rem",
    sm: ".5rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "2rem",
    xxl: "3rem",
    xxxl: "4rem",
  },
  breakpoints: { tablet: 640, desktop: 1024 },
  layout: { maxWidth: "1240px", touchTarget: "44px" },
  shadows: {
    card: "0 2px 8px -2px rgb(25 28 30 / .04), 0 1px 3px rgb(25 28 30 / .06)",
    floating:
      "0 8px 24px -4px rgb(25 28 30 / .08), 0 3px 6px -1px rgb(25 28 30 / .04)",
    overlay: "0 20px 48px -8px rgb(25 28 30 / .16)",
  },
  motion: { fast: "150ms", normal: "220ms" },
  zIndex: { dropdown: 1000, sticky: 1020, modal: 1050, toast: 1080 },
} as const;
