import React, { useMemo, useState } from "react";
import { Building2, Camera, Check, ChevronRight, Crown, Edit3, FileText, Mail, MapPin, MoreHorizontal, Phone, Plus, Search, Settings, ShieldCheck, Store, Trash2, Upload, Users } from "lucide-react";
import { uid, useDemo, type Document, type Staff } from "../model";
import { CountTile, Field, HeaderTitle, Modal, Pill } from "../MerchantPrototype";
const staffBlank=(branch:string):Staff=>({id:"",name:"",email:"",phone:"",role:"Staff",branch,status:"Pending"});
type Role="Owner"|"Manager"|"Staff";
const defaultPermission:Record<Role,string[]>={Owner:["Kitchen orders","Menu management","Finance & settlements","Team management","Branch settings","Security"],Manager:["Kitchen orders","Menu management","Branch settings"],Staff:["Kitchen orders","Menu management"]};
export function TeamPage({search,navigate}:{search:string;navigate:(page:string)=>void}){
 const {data,update,announce}=useDemo();
 const [query,setQuery]=useState("");
 const [statusFilter,setStatusFilter]=useState("All members");
 const [roleFilter,setRoleFilter]=useState("All roles");
 const [branchFilter,setBranchFilter]=useState("All branches");
 const [profileOpen,setProfileOpen]=useState(false);
 const [profile,setProfile]=useState(data.business);
 const [member,setMember]=useState<Staff|null>(null);
 const [actionMenu,setActionMenu]=useState<string|null>(null);
 const [document,setDocument]=useState<Document|null>(null);
 const [docOpen,setDocOpen]=useState(false);
 const [docLabel,setDocLabel]=useState("Business registration");
 const [docFile,setDocFile]=useState<File|null>(null);
 const [rolesOpen,setRolesOpen]=useState(false);
 const [permissions,setPermissions]=useState(defaultPermission);
 const active=data.staff.filter(s=>s.status==="Active").length;
 const pending=data.staff.filter(s=>s.status==="Pending").length;
 const filtered=useMemo(()=>data.staff.filter(s=>{
 if(statusFilter!=="All members"&&s.status!==statusFilter)return false;
 if(roleFilter!=="All roles"&&s.role!==roleFilter)return false;
 if(branchFilter!=="All branches"&&s.branch!==branchFilter&&s.branch!=="All branches")return false;
 const term=(search+" "+query).trim().toLowerCase();
 if(term&&![s.name,s.email,s.phone,s.role,s.branch].some(x=>x.toLowerCase().includes(term)))return false;
 return true;
 }),[data.staff,statusFilter,roleFilter,branchFilter,query,search]);
 const saveProfile=(e:React.FormEvent)=>{e.preventDefault();update(p=>({...p,business:profile}));setProfileOpen(false);announce("Business profile saved locally");};
 const saveMember=(e:React.FormEvent)=>{e.preventDefault();if(!member)return;const updated={...member,id:member.id||uid()};update(p=>({...p,staff:member.id?p.staff.map(s=>s.id===updated.id?updated:s):[...p.staff,updated]}));setMember(null);announce(member.id?"Team member updated":"Invitation created (prototype only)");};
 const setStaffStatus=(id:string,status:Staff["status"])=>{update(p=>({...p,staff:p.staff.map(s=>s.id===id?{...s,status}:s)}));setActionMenu(null);announce("Team membership changed to "+status);};
 const addDocument=(e:React.FormEvent)=>{e.preventDefault();if(!docFile)return;update(p=>({...p,documents:[...p.documents,{id:uid(),name:docLabel,filename:docFile.name,date:new Date().toLocaleDateString("en-GB",{month:"short",day:"numeric",year:"numeric"}),status:"Pending"}]}));setDocOpen(false);setDocFile(null);announce("Document added locally; verification pending");};
 const avatar=(s:Staff)=>s.name.split(/\s+/).map(x=>x[0]).slice(0,2).join("").toUpperCase();
 const roleTone=(role:Role)=>role==="Owner"?"purple":role==="Manager"?"blue":"gray";
 return <div className="mp-page mp-business-page">
 <HeaderTitle eyebrow="Business" title="Business & team" description="Manage your business profile and give your team the right access to run your restaurant."/>
 <div className="mp-stat-grid">
 <CountTile icon={Store} label="Team members" value={data.staff.length} caption={active+" active · "+pending+" pending"} accent="mint" action={()=>setStatusFilter("All members")}/>
 <CountTile icon={ShieldCheck} label="Roles" value={new Set(data.staff.map(s=>s.role)).size} caption="Owner, Manager, Staff" accent="purple" action={()=>setRolesOpen(true)}/>
 <CountTile icon={Building2} label="Branches" value="1" caption={data.branch+" (Active)"} accent="orange" action={()=>navigate("branch")}/>
 <CountTile icon={Users} label="Pending invites" value={pending} caption="Expires in 6 days · demo" accent="blue" action={()=>setStatusFilter("Pending")}/>
 </div>
 <div className="mp-business-grid">
 <section className="mp-panel mp-business-profile"><div className="mp-panel-heading"><div><h2>Business profile</h2><p>This information appears to customers on DeeToo.</p></div><button className="mp-outline" onClick={()=>{setProfile({...data.business});setProfileOpen(true);}}><Edit3 size={16}/> Edit profile</button></div>
 <div className="mp-business-intro"><div className="mp-business-image"><img src="https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&q=85" alt="Restaurant storefront" onError={e=>e.currentTarget.style.display="none"}/><button aria-label="Change business photo" onClick={()=>{setProfile({...data.business});setProfileOpen(true);}}><Camera size={20}/></button></div>
 <div className="mp-profile-intro-copy"><span>Legal name</span><strong>{data.business.legalName}</strong><span>Display name</span><strong>{data.business.displayName}</strong><span>Business description</span><strong>{data.business.description}</strong></div></div>
 <div className="mp-business-identity"><div><Store size={18}/><span><strong>Business type</strong><small>{data.business.type}</small></span></div><div><MapPin size={18}/><span><strong>Street address</strong><small>{data.business.address}</small></span></div><div><Phone size={18}/><span><strong>Phone</strong><small>{data.business.phone}</small></span></div><div><MapPin size={18}/><span><strong>Operating country</strong><small>{data.business.country}</small></span></div><div><Mail size={18}/><span><strong>Email</strong><small>{data.business.email}</small></span></div></div>
 <div className="mp-documents"><div className="mp-panel-heading"><div><h2>Business documents</h2><p>Keep your business documents up to date.</p></div><button className="mp-primary" onClick={()=>{setDocFile(null);setDocOpen(true);}}>+ Add document</button></div>
 {data.documents.map(doc=><div className="mp-document-row" key={doc.id}><span className="mp-doc-icon"><FileText size={19}/></span><div><strong>{doc.name}</strong><small>{doc.filename}</small></div><Pill tone={doc.status==="Verified"?"green":doc.status==="Pending"?"amber":"red"}>{doc.status}</Pill><small>{doc.date}</small><button aria-label={"Document actions "+doc.name} onClick={()=>setDocument(doc)}><MoreHorizontal size={20}/></button></div>)}
 </div></section>
 <section className="mp-panel mp-team-panel"><div className="mp-panel-heading"><div><h2>Team members</h2><p>Invite staff and manage their access across all your branches.</p></div><button className="mp-primary" onClick={()=>setMember(staffBlank(data.branch))}><Plus size={20}/> Invite team member</button></div>
 <div className="mp-tabs mp-team-tabs">{[["All members",data.staff.length],["Active",active],["Pending",pending],["Inactive",data.staff.filter(x=>x.status==="Inactive").length]].map(([k,n])=><button key={k} className={statusFilter===k?"mp-light-active":""} aria-pressed={statusFilter===k} onClick={()=>setStatusFilter(String(k))}>{k} ({n})</button>)}</div>
 <div className="mp-team-filters"><label className="mp-local-search"><Search size={17}/><input aria-label="Search team members" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search team members..."/></label><select value={roleFilter} aria-label="Role filter" onChange={e=>setRoleFilter(e.target.value)}><option>All roles</option><option>Owner</option><option>Manager</option><option>Staff</option></select><select value={branchFilter} aria-label="Branch filter" onChange={e=>setBranchFilter(e.target.value)}><option>All branches</option>{data.branches.map(b=><option key={b}>{b}</option>)}</select></div>
 <div className="mp-table-scroll"><table className="mp-team-table"><thead><tr><th>Name</th><th>Email / Phone</th><th>Role</th><th>Branch access</th><th>Status</th><th>Actions</th></tr></thead><tbody>
 {filtered.map(person=><tr key={person.id}><td><div className="mp-person-name"><span className={"mp-staff-avatar mp-avatar-"+person.role.toLowerCase()}>{avatar(person)}</span><div><strong>{person.name}{person.role==="Owner"&&" 👑"}</strong><small>{person.role}</small></div></div></td><td>{person.email}<small>{person.phone}</small></td><td><Pill tone={roleTone(person.role)}>{person.role}</Pill></td><td>{person.branch}</td><td><Pill tone={person.status==="Active"?"green":person.status==="Pending"?"amber":"gray"}>{person.status}</Pill></td><td><div className="mp-popover-anchor"><button className="mp-icon-button" aria-label={"Actions for "+person.name} onClick={()=>setActionMenu(actionMenu===person.id?null:person.id)}><MoreHorizontal size={21}/></button>{actionMenu===person.id&&<div className="mp-row-menu"><button onClick={()=>{setMember({...person});setActionMenu(null);}}>Edit access</button>{person.status==="Pending"&&<button onClick={()=>{setActionMenu(null);announce("Invitation resent in prototype");}}>Resend invitation</button>}{person.role!=="Owner"&&<button onClick={()=>setStaffStatus(person.id,person.status==="Inactive"?"Active":"Inactive")}>{person.status==="Inactive"?"Reactivate":"Deactivate"}</button>}</div>}</div></td></tr>)}
 </tbody></table>{!filtered.length&&<div className="mp-no-items"><h3>No members found</h3><p>Adjust filters or invite a new team member.</p></div>}</div>
 <div className="mp-roles-area"><div className="mp-panel-heading"><div><h2><ShieldCheck size={23}/> Roles and permissions</h2><p>Control what your team members can access and do.</p></div><button className="mp-outline" onClick={()=>setRolesOpen(true)}><Settings size={18}/> Manage roles</button></div><div className="mp-role-cards">
 {(["Owner","Manager","Staff"] as const).map(role=><button key={role} onClick={()=>setRolesOpen(true)} className="mp-role-card"><span className={"mp-role-glyph mp-role-"+role.toLowerCase()}>{role==="Owner"?<Crown size={21}/>:role==="Manager"?<Users size={21}/>:<ShieldCheck size={21}/>}</span><div><strong>{role}</strong><p>{role==="Owner"?"Full access to all features and settings.":role==="Manager"?"Can manage menu, orders and daily operations.":"Can manage kitchen orders and update menu items."}</p></div></button>)}</div></div>
 </section>
 </div>
 <Modal open={profileOpen} title="Edit business profile" onClose={()=>setProfileOpen(false)} width="620px"><form className="mp-form-grid" onSubmit={saveProfile}>
 {(["legalName","displayName","type","phone","email","address","country"] as const).map(key=><Field key={key} label={key.replace(/([A-Z])/g," $1")}><input required value={profile[key]} onChange={e=>setProfile({...profile,[key]:e.target.value})}/></Field>)}
 <Field label="Description"><textarea value={profile.description} rows={3} onChange={e=>setProfile({...profile,description:e.target.value})}/></Field>
 <Field label="Storefront image"><input type="file" accept="image/*" onChange={()=>announce("Photo selected; upload backend will be mapped after Phase 2")}/></Field>
 <div className="mp-dialog-actions"><button type="button" className="mp-outline" onClick={()=>setProfileOpen(false)}>Cancel</button><button className="mp-primary" type="submit">Save profile</button></div></form></Modal>
 <Modal open={Boolean(member)} title={member?.id?"Edit team access":"Invite team member"} onClose={()=>setMember(null)}>
 {member&&<form className="mp-form-grid" onSubmit={saveMember}><Field label="Full name *"><input required value={member.name} onChange={e=>setMember({...member,name:e.target.value})}/></Field><Field label="Email *"><input type="email" required value={member.email} onChange={e=>setMember({...member,email:e.target.value})}/></Field><Field label="Phone"><input type="tel" value={member.phone} onChange={e=>setMember({...member,phone:e.target.value})}/></Field><Field label="Role"><select value={member.role} onChange={e=>setMember({...member,role:e.target.value as Staff["role"]})}><option>Owner</option><option>Manager</option><option>Staff</option></select></Field><Field label="Branch access"><select value={member.branch} onChange={e=>setMember({...member,branch:e.target.value})}><option>All branches</option>{data.branches.map(b=><option key={b}>{b}</option>)}</select></Field><Field label="Status"><select value={member.status} onChange={e=>setMember({...member,status:e.target.value as Staff["status"]})}><option>Active</option><option>Pending</option><option>Inactive</option></select></Field>
 <div className="mp-dialog-actions"><button type="button" className="mp-outline" onClick={()=>setMember(null)}>Cancel</button><button className="mp-primary" type="submit">{member.id?"Save access":"Send invitation"}</button></div></form>}
 </Modal>
 <Modal open={docOpen} title="Add business document" onClose={()=>setDocOpen(false)}><form onSubmit={addDocument} className="mp-form-grid"><Field label="Document type"><select value={docLabel} onChange={e=>setDocLabel(e.target.value)}><option>Business registration</option><option>KRA PIN Certificate</option><option>Food handling certificate</option><option>Other document</option></select></Field><Field label="Choose file *"><input type="file" required accept=".pdf,.png,.jpeg,.jpg" onChange={e=>setDocFile(e.target.files?.[0]||null)}/></Field><p className="mp-muted">Files are not uploaded to a server in this prototype. Only the selected filename is saved locally.</p><div className="mp-dialog-actions"><button type="button" className="mp-outline" onClick={()=>setDocOpen(false)}>Cancel</button><button className="mp-primary" type="submit">Add document</button></div></form></Modal>
 <Modal open={Boolean(document)} title={document?.name||"Business document"} onClose={()=>setDocument(null)}><div className="mp-detail-stack"><div><small>Filename</small><strong>{document?.filename}</strong></div><div><small>Verification status</small><strong>{document?.status}</strong></div><div><small>Added</small><strong>{document?.date}</strong></div></div><p className="mp-muted">This is a simulated document record; file download and verification require backend support.</p><div className="mp-dialog-actions"><button className="mp-outline" onClick={()=>setDocument(null)}>Close</button><button className="mp-danger" onClick={()=>{if(document)update(p=>({...p,documents:p.documents.filter(d=>d.id!==document.id)}));setDocument(null);announce("Document record removed locally");}}>Remove record</button></div></Modal>
 <Modal open={rolesOpen} title="Manage roles and permissions" onClose={()=>setRolesOpen(false)} width="700px"><p className="mp-muted">Prototype permissions matrix. These changes do not grant actual server access.</p><div className="mp-permissions-table"><table><thead><tr><th>Capability</th><th>Owner</th><th>Manager</th><th>Staff</th></tr></thead><tbody>{["Kitchen orders","Menu management","Finance & settlements","Team management","Branch settings","Security"].map(cap=><tr key={cap}><td>{cap}</td>{(["Owner","Manager","Staff"] as const).map(role=><td key={role}><input aria-label={role+" can access "+cap} type="checkbox" checked={permissions[role].includes(cap)} onChange={e=>setPermissions(prev=>({...prev,[role]:e.target.checked?[...prev[role],cap]:prev[role].filter(x=>x!==cap)}))}/></td>)}</tr>)}</tbody></table></div><div className="mp-dialog-actions"><button className="mp-outline" onClick={()=>setRolesOpen(false)}>Cancel</button><button className="mp-primary" onClick={()=>{setRolesOpen(false);announce("Permissions saved as UI prototype only");}}>Save permissions</button></div></Modal>
 </div>;
}
